import type { Lang } from './i18n';

export interface DhikrItem {
  ar: string;
  transliteration: string;
  translations: Partial<Record<Lang, string>>;
}

export const DHIKR_ITEMS: DhikrItem[] = [
  {
    ar: 'سُبْحَانَ اللَّهِ',
    transliteration: 'Subḥānallāh',
    translations: {
      en: 'Glory be to Allah',
      fr: 'Gloire à Allah',
      es: 'Gloria a Allah',
      ru: 'Слава Аллаху',
      zh: '赞美安拉',
      tr: 'Allah\'ı tesbih ederim',
      ur: 'اللہ پاک ہے',
      id: 'Maha Suci Allah',
      bn: 'আল্লাহ পবিত্র',
      fa: 'پاک است خدا',
      ms: 'Maha Suci Allah',
      pt: 'Glória a Allah',
      sw: 'Utukufu ni wa Allah',
      ha: 'Tsarki ya tabbata ga Allah',
    },
  },
  {
    ar: 'الْحَمْدُ لِلَّهِ',
    transliteration: 'Alḥamdulillāh',
    translations: {
      en: 'All praise is due to Allah',
      fr: 'Toute louange est due à Allah',
      es: 'Toda alabanza es para Allah',
      ru: 'Вся хвала Аллаху',
      zh: '一切赞美归于安拉',
      tr: 'Hamd Allah\'a aittir',
      ur: 'تمام تعریفیں اللہ کے لیے',
      id: 'Segala puji bagi Allah',
      bn: 'সকল প্রশংসা আল্লাহর',
      fa: 'همه ستایش از آن خداست',
      ms: 'Segala puji bagi Allah',
      pt: 'Todo louvor pertence a Allah',
      sw: 'Sifa zote ni za Allah',
      ha: 'Godiya ta tabbata ga Allah',
    },
  },
  {
    ar: 'اللَّهُ أَكْبَرُ',
    transliteration: 'Allāhu Akbar',
    translations: {
      en: 'Allah is the Greatest',
      fr: 'Allah est le Plus Grand',
      es: 'Allah es el Más Grande',
      ru: 'Аллах Велик',
      zh: '安拉至大',
      tr: 'Allah en büyüktür',
      ur: 'اللہ سب سے بڑا ہے',
      id: 'Allah Maha Besar',
      bn: 'আল্লাহ সর্বশ্রেষ্ঠ',
      fa: 'خدا بزرگ‌تر است',
      ms: 'Allah Maha Besar',
      pt: 'Allah é o Maior',
      sw: 'Allah ni Mkubwa',
      ha: 'Allah ya fi girma',
    },
  },
  {
    ar: 'لَا إِلَهَ إِلَّا اللَّهُ',
    transliteration: 'Lā ilāha illallāh',
    translations: {
      en: 'There is no god but Allah',
      fr: 'Il n\'y a de dieu qu\'Allah',
      es: 'No hay dios salvo Allah',
      ru: 'Нет бога кроме Аллаха',
      zh: '除安拉外别无神灵',
      tr: 'Allah\'tan başka ilah yoktur',
      ur: 'اللہ کے سوا کوئی معبود نہیں',
      id: 'Tidak ada tuhan selain Allah',
      bn: 'আল্লাহ ছাড়া কোনো ইলাহ নেই',
      fa: 'هیچ خدایی جز الله نیست',
      ms: 'Tiada tuhan melainkan Allah',
      pt: 'Não há deus senão Allah',
      sw: 'Hakuna mungu ila Allah',
      ha: 'Babu abin bautawa sai Allah',
    },
  },
  {
    ar: 'أَسْتَغْفِرُ اللَّهَ',
    transliteration: 'Astaghfirullāh',
    translations: {
      en: 'I seek forgiveness from Allah',
      fr: 'Je demande pardon à Allah',
      es: 'Pido perdón a Allah',
      ru: 'Прошу прощения у Аллаха',
      zh: '我向安拉悔罪',
      tr: 'Allah\'tan bağışlanma dilerim',
      ur: 'میں اللہ سے معافی مانگتا ہوں',
      id: 'Aku memohon ampun kepada Allah',
      bn: 'আমি আল্লাহর কাছে ক্ষমা চাই',
      fa: 'از خدا آمرزش می‌خواهم',
      ms: 'Aku memohon keampunan Allah',
      pt: 'Peço perdão a Allah',
      sw: 'Ninaomba msamaha kwa Allah',
      ha: 'Ina neman gafara daga Allah',
    },
  },
  {
    ar: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
    transliteration: 'Subḥānallāhi wa biḥamdih',
    translations: {
      en: 'Glory and praise be to Allah',
      fr: 'Gloire et louange à Allah',
      es: 'Gloria y alabanza a Allah',
      ru: 'Слава Аллаху и хвала Ему',
      zh: '赞美并颂扬安拉',
      tr: 'Allah\'ı hamd ile tesbih ederim',
      ur: 'اللہ کی تسبیح اور حمد',
      id: 'Maha Suci Allah dan segala puji bagi-Nya',
      bn: 'আল্লাহ পবিত্র ও তাঁর প্রশংসা',
      fa: 'خدا را ستایش می‌کنم',
      ms: 'Maha Suci Allah dan segala pujian bagi-Nya',
      pt: 'Glória e louvor a Allah',
      sw: 'Utukufu na sifa zote ni za Allah',
      ha: 'Tsarki da godiya sun tabbata ga Allah',
    },
  },
  {
    ar: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: 'Lā ḥawla wa lā quwwata illā billāh',
    translations: {
      en: 'There is no power except with Allah',
      fr: 'Il n\'y a de force qu\'en Allah',
      es: 'No hay fuerza sino en Allah',
      ru: 'Нет силы и мощи, кроме как от Аллаха',
      zh: '一切能力与力量唯属安拉',
      tr: 'Güç ve kuvvet yalnızca Allah\'a aittir',
      ur: 'اللہ کے سوا کوئی طاقت نہیں',
      id: 'Tidak ada daya dan kekuatan kecuali dari Allah',
      bn: 'আল্লাহ ছাড়া কোনো শক্তি নেই',
      fa: 'هیچ نیرو و توانی جز از خدا نیست',
      ms: 'Tiada daya dan kekuatan melainkan dengan Allah',
      pt: 'Não há poder senão de Allah',
      sw: 'Hakuna nguvu wala uwezo ila kwa Allah',
      ha: 'Babu iko ko ƙarfi sai da Allah',
    },
  },
  {
    ar: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ',
    transliteration: 'Allāhumma ṣalli ʿalā Muḥammad',
    translations: {
      en: 'O Allah, send blessings upon Muhammad',
      fr: 'Ô Allah, envoie des bénédictions sur Muhammad',
      es: 'Oh Allah, envía bendiciones sobre Muhammad',
      ru: 'О Аллах, благослови Мухаммада',
      zh: '主啊，求您赐福穆罕默德',
      tr: 'Allah\'ım, Muhammed\'e salat eyle',
      ur: 'اے اللہ، محمد ﷺ پر درود بھیج',
      id: 'Ya Allah, limpahkan shalawat atas Muhammad',
      bn: 'হে আল্লাহ, মুহাম্মদের উপর দরূদ পাঠাও',
      fa: 'خداوندا، بر محمد درود فرست',
      ms: 'Ya Allah, selawatlah ke atas Muhammad',
      pt: 'Ó Allah, abençoa Muhammad',
      sw: 'Ee Allah, salia juu ya Muhammad',
      ha: 'Ya Allah ka yi salati a kan Muhammad',
    },
  },
  {
    ar: 'حَسْبِيَ اللَّهُ وَنِعْمَ الْوَكِيلُ',
    transliteration: 'Ḥasbiyallāhu wa niʿmal wakīl',
    translations: {
      en: 'Allah is sufficient for me and He is the best Trustee',
      fr: 'Allah me suffit, Il est le meilleur garant',
      es: 'Allah me basta, Él es el mejor garante',
      ru: 'Аллах мне достаточен и лучший покровитель',
      zh: '安拉对我已足够，祂是最好的监护人',
      tr: 'Allah bana yeter, O ne güzel vekildir',
      ur: 'اللہ مجھے کافی ہے اور وہ بہترین وکیل ہے',
      id: 'Cukuplah Allah bagiku dan Dialah sebaik-baik pelindung',
      bn: 'আল্লাহই আমার জন্য যথেষ্ট এবং তিনি সর্বোত্তম অভিভাবক',
      fa: 'خدا مرا کافی است و بهترین وکیل است',
      ms: 'Cukuplah Allah bagiku dan Dialah sebaik-baik penjaga',
      pt: 'Allah me basta e Ele é o melhor protetor',
      sw: 'Allah yanitosha na yeye ndiye mlinzi bora',
      ha: 'Allah ya isa mini, shi ne mafi kyawun mai kula',
    },
  },
  {
    ar: 'اللَّهُمَّ اغْفِرْ لِي',
    transliteration: 'Allāhumma ghfir lī',
    translations: {
      en: 'O Allah, forgive me',
      fr: 'Ô Allah, pardonne-moi',
      es: 'Oh Allah, perdóname',
      ru: 'О Аллах, прости меня',
      zh: '主啊，请宽恕我',
      tr: 'Allah\'ım, beni bağışla',
      ur: 'اے اللہ، مجھے معاف کر دے',
      id: 'Ya Allah, ampunilah aku',
      bn: 'হে আল্লাহ, আমাকে ক্ষমা কর',
      fa: 'خداوندا، مرا ببخش',
      ms: 'Ya Allah, ampunilah aku',
      pt: 'Ó Allah, perdoa-me',
      sw: 'Ee Allah, nisamehe',
      ha: 'Ya Allah ka gafarce ni',
    },
  },
  {
    ar: 'رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ',
    transliteration: 'Rabbi ghfir lī wa tub ʿalayya',
    translations: {
      en: 'My Lord, forgive me and accept my repentance',
      fr: 'Seigneur, pardonne-moi et accepte mon repentir',
      es: 'Señor, perdóname y acepta mi arrepentimiento',
      ru: 'Господи, прости меня и прими моё покаяние',
      zh: '我的主，请宽恕我并接受我的悔过',
      tr: 'Rabbim, beni bağışla ve tevbemi kabul et',
      ur: 'اے میرے رب، مجھے معاف کر اور میری توبہ قبول فرما',
      id: 'Tuhanku, ampunilah aku dan terimalah taubatku',
      bn: 'হে আমার রব, আমাকে ক্ষমা কর এবং আমার তওবা কবুল কর',
      fa: 'پروردگارم، مرا ببخش و توبه‌ام را بپذیر',
      ms: 'Tuhanku, ampunilah aku dan terimalah taubatku',
      pt: 'Senhor, perdoa-me e aceita o meu arrependimento',
      sw: 'Mola wangu, nisamehe na ukubali toba yangu',
      ha: 'Ubangijina ka gafarce ni kuma ka karɓi tuba ta',
    },
  },
  {
    ar: 'سُبْحَانَ اللَّهِ الْعَظِيمِ',
    transliteration: 'Subḥānallāhil ʿAẓīm',
    translations: {
      en: 'Glory be to Allah the Almighty',
      fr: 'Gloire à Allah le Très Grand',
      es: 'Gloria a Allah el Todopoderoso',
      ru: 'Слава Аллаху Величайшему',
      zh: '赞美伟大的安拉',
      tr: 'Yüce Allah\'ı tesbih ederim',
      ur: 'اللہ عظیم کی تسبیح',
      id: 'Maha Suci Allah Yang Maha Agung',
      bn: 'মহান আল্লাহর পবিত্রতা',
      fa: 'پاک است خداوند بزرگ',
      ms: 'Maha Suci Allah Yang Maha Agung',
      pt: 'Glória a Allah o Todo-Poderoso',
      sw: 'Utukufu ni wa Allah Mtukufu',
      ha: 'Tsarki ya tabbata ga Allah Mai Girma',
    },
  },
  {
    ar: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ',
    transliteration: 'Yā Ḥayyu Yā Qayyūmu biraḥmatika astaghīth',
    translations: {
      en: 'O Ever-Living, O Sustainer, in Your mercy I seek relief',
      fr: 'Ô Vivant, ô Subsistant, je cherche secours en Ta miséricorde',
      es: 'Oh Viviente, oh Sustentador, en Tu misericordia busco alivio',
      ru: 'О Живой, о Вседержащий, я взываю к Твоей милости',
      zh: '啊，永恒的真主，我以您的慈悯求助',
      tr: 'Ey Hayy, ey Kayyum, rahmetinle yardım dilerim',
      ur: 'اے زندہ، اے قائم، تیری رحمت سے فریاد کرتا ہوں',
      id: 'Wahai Yang Maha Hidup, wahai Yang Maha Berdiri sendiri, dengan rahmat-Mu aku memohon pertolongan',
      bn: 'হে চিরজীবী, হে চিরসত্তা, তোমার রহমতে সাহায্য চাই',
      fa: 'ای زنده ابدی، ای پاینده، به رحمتت استغاثه می‌کنم',
      ms: 'Wahai Yang Maha Hidup, wahai Yang Maha Berdiri, dengan rahmat-Mu aku memohon pertolongan',
      pt: 'Ó Sempre-Vivo, ó Sustentador, em Tua misericórdia busco refúgio',
      sw: 'Ee Mwenye Uhai wa Milele, Ee Mwenye Kudumu, natafuta msaada katika rehma Yako',
      ha: 'Ya Mai Rai, ya Mai Tsayuwa, da rahamararka ina neman taimako',
    },
  },
  {
    ar: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ',
    transliteration: 'Allāhumma innī asʾaluka l-ʿāfiyah',
    translations: {
      en: 'O Allah, I ask You for well-being',
      fr: 'Ô Allah, je Te demande la santé et le bien-être',
      es: 'Oh Allah, te pido bienestar y salud',
      ru: 'О Аллах, прошу Тебя о благополучии',
      zh: '主啊，我求您赐予平安健康',
      tr: 'Allah\'ım, senden afiyet istiyorum',
      ur: 'اے اللہ، میں تجھ سے عافیت مانگتا ہوں',
      id: 'Ya Allah, aku memohon kepada-Mu keselamatan',
      bn: 'হে আল্লাহ, আমি তোমার কাছে সুস্থতা চাই',
      fa: 'خداوندا، از تو عافیت می‌خواهم',
      ms: 'Ya Allah, aku memohon kepada-Mu kesejahteraan',
      pt: 'Ó Allah, peço-Te saúde e bem-estar',
      sw: 'Ee Allah, nakuomba afya na usalama',
      ha: 'Ya Allah ina roƙonka lafiya',
    },
  },
  {
    ar: 'رَضِيتُ بِاللَّهِ رَبًّا وَبِالْإِسْلَامِ دِينًا وَبِمُحَمَّدٍ نَبِيًّا',
    transliteration: 'Raḍītu billāhi Rabban wa bil-Islāmi dīnan wa bi-Muḥammadin nabiyyan',
    translations: {
      en: 'I am pleased with Allah as my Lord, Islam as my religion, and Muhammad as my Prophet',
      fr: 'Je suis satisfait d\'Allah comme Seigneur, de l\'Islam comme religion et de Muhammad comme prophète',
      es: 'Estoy complacido con Allah como mi Señor, el Islam como mi religión y Muhammad como mi Profeta',
      ru: 'Я доволен Аллахом как Господом, Исламом как религией и Мухаммадом как пророком',
      zh: '我以安拉为主，以伊斯兰为宗教，以穆罕默德为先知而满足',
      tr: 'Allah\'ı Rabbim, İslam\'ı dinim, Muhammed\'i Nebim olarak kabul ettim',
      ur: 'میں اللہ کو رب، اسلام کو دین اور محمد ﷺ کو نبی مانتے ہوئے راضی ہوں',
      id: 'Aku ridha Allah sebagai Tuhanku, Islam sebagai agamaku, dan Muhammad sebagai Nabiku',
      bn: 'আমি আল্লাহকে রব, ইসলামকে দ্বীন এবং মুহাম্মদকে নবী হিসেবে সন্তুষ্ট',
      fa: 'به رب بودن خدا، دین بودن اسلام و نبوت محمد راضی هستم',
      ms: 'Aku redha Allah sebagai Tuhanku, Islam sebagai agamaku dan Muhammad sebagai Nabiku',
      pt: 'Estou satisfeito com Allah como meu Senhor, o Islão como minha religião e Muhammad como meu Profeta',
      sw: 'Nimeridhika na Allah kama Mola wangu, Uislamu kama dini yangu, na Muhammad kama Nabii wangu',
      ha: 'Na yarda da Allah a matsayin Ubangijina, Musulunci a matsayin addinin na da kuma Muhammad a matsayin Annabina',
    },
  },
];

export const DHIKR_TIMES = ['07:00', '10:00', '13:30', '16:30', '20:00'];

export function getDhikrText(item: DhikrItem, lang: Lang): string {
  if (lang === 'ar') return item.ar;
  return item.translations[lang] ?? item.translations.en ?? item.ar;
}
