/**
 * Authentic Athkar - Morning & Evening Remembrances
 * Sources: Hisn al-Muslim, Sahih Bukhari, Sahih Muslim, Abu Dawud, Tirmidhi
 */

export interface Thikr {
  id: string;
  arabic: string;
  transliteration: string;
  translations: Partial<Record<string, string>>;
  count: number;          // required repetitions
  source: string;         // hadith reference (Arabic short form)
  sourceEn: string;       // hadith reference (English)
  virtue?: Partial<Record<string, string>>; // optional benefit text
}

export interface AthkarSet {
  morning: Thikr[];
  evening: Thikr[];
}

const ATHKAR: AthkarSet = {
  morning: [
    {
      id: 'morning_14',
      arabic: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ\n﴿اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ﴾',
      transliteration: "A'udhu billahi minash-shaytanir-rajim. Allahu la ilaha illa huwal-hayyul-qayyum, la ta'khudhuhu sinatun wa la nawm, lahu ma fis-samawati wa ma fil-ard, man dhal-ladhi yashfa'u 'indahu illa bi'idhnin, ya'lamu ma bayna aydihim wa ma khalfahum wa la yuhituna bishay'in min 'ilmihi illa bima sha', wasi'a kursiyyuhus-samawati wal-ard, wa la ya'uduhu hifzuhuma wa huwal-'aliyyul-'azim.",
      translations: {
        en: "Allah! None has the right to be worshipped but He, the Ever-Living, the One Who sustains and protects all that exists. Neither slumber nor sleep overtakes Him. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His throne extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great. (Ayat al-Kursi, Al-Baqarah 2:255)",
        fr: "Allah! Point de divinité à part Lui, le Vivant, Celui qui subsiste par lui-même. Ni la somnolence ni le sommeil ne Le saisissent. À Lui appartient tout ce qui est dans les cieux et sur la terre. Qui peut intercéder auprès de Lui sans Sa permission? (Verset du Trône, Al-Baqarah 2:255)",
        tr: "Allah, O'ndan başka tanrı yoktur. O, daima diri ve daima yarattıklarını gözetip durandır. Onu ne bir uyuklama ne de uyku yakalar. Göklerdekiler ve yerdekiler hep O'nundur. (Ayet'el Kürsi, Bakara 2/255)",
        ur: "اللہ، اس کے سوا کوئی معبود نہیں، وہ ہمیشہ زندہ اور قائم رہنے والا ہے، اسے نہ اونگھ آتی ہے نہ نیند۔ (آیة الکرسی، البقرة ٢:٢٥٥)",
        id: "Allah, tidak ada Tuhan selain Dia. Yang Maha Hidup, yang terus-menerus mengurus (makhluk-Nya). Tidak mengantuk dan tidak tidur. Milik-Nya apa yang ada di langit dan apa yang ada di bumi. (Ayat Al-Kursi, Al-Baqarah 2:255)",
        ms: "Allah, tiada Tuhan selain-Nya, Yang Maha Hidup, Yang Terus menerus mengurus (makhluk-Nya). (Ayat al-Kursi, Al-Baqarah 2:255)",
        fa: "خداوند، هیچ معبودی جز او نیست، زنده‌ای پاینده است. نه چرت او را فرا می‌گیرد و نه خواب. (آیةالکرسی، البقره ۲:۲۵۵)",
      },
      count: 1,
      source: 'البخاري ٢٣١١، أبو داود ١٥٢٣',
      sourceEn: 'Bukhari 2311, Abu Dawud 1523',
      virtue: {
        ar: 'من قرأ آية الكرسي حين يصبح أُجير من الجن حتى يمسي',
        en: 'Whoever recites Ayat al-Kursi in the morning will be protected from jinn until the evening.',
        fr: "Quiconque récite le Verset du Trône le matin sera protégé des djinns jusqu'au soir.",
        tr: "Sabah Ayetel Kürsi'yi okuyan, akşama kadar cinlerden korunur.",
        ur: "جو صبح آیة الکرسی پڑھے وہ شام تک جنات سے محفوظ رہتا ہے۔",
      },
    },
    {
      id: 'morning_15',
      arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ، اللَّهُ الصَّمَدُ، لَمْ يَلِدْ وَلَمْ يُولَدْ، وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
      transliteration: "Qul huwallahu ahad, Allahus-samad, lam yalid wa lam yulad, wa lam yakullahu kufuwan ahad.",
      translations: {
        en: "Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. Nor is there to Him any equivalent. (Surah Al-Ikhlas 112)",
        fr: "Dis: Il est Allah, l'Unique. Allah, le Seul à être imploré pour ce que nous désirons. Il n'a jamais engendré, n'a pas été engendré non plus. Et nul n'est égal à Lui. (Sourate Al-Ikhlas 112)",
        tr: "De ki: O, Allah'tır, bir tektir. Allah Samed'dir. O doğurmamış ve doğurulmamıştır. Hiçbir şey O'na denk değildir. (İhlas Suresi 112)",
        ur: "کہو: وہ اللہ ایک ہے، اللہ بے نیاز ہے، نہ اس نے کسی کو جنا اور نہ وہ کسی سے جنا گیا، اور کوئی اس کا ہمسر نہیں۔ (سورة الاخلاص ١١٢)",
        id: "Katakanlah: Dialah Allah, Yang Maha Esa. Allah adalah Tuhan yang bergantung kepada-Nya segala sesuatu. Dia tiada beranak dan tidak pula diperanakkan. Dan tidak ada seorangpun yang setara dengan Dia. (Surah Al-Ikhlas 112)",
        ms: "Katakanlah (wahai Muhammad): Allah itu Maha Esa. Allah yang menjadi tumpuan sekalian makhluk untuk memohon sebarang hajat. Ia tiada beranak, dan Ia pula tidak diperanakkan. Dan tidak ada sesiapapun yang serupa denganNya. (Surah Al-Ikhlas 112)",
        fa: "بگو: اوست خداوند یکتا. خداوند بی‌نیاز. نزاد و زاده نشد. و هیچ‌کس همتای او نیست. (سوره الاخلاص ۱۱۲)",
      },
      count: 3,
      source: 'أبو داود ٥٠٨٢، النسائي ٥٤٢٨',
      sourceEn: 'Abu Dawud 5082, An-Nasai 5428',
      virtue: {
        ar: 'كفته من كل شيء',
        en: "Suffices for all things (reciting Al-Ikhlas and Al-Mu'awwidhatayn 3x morning and evening).",
        fr: "Suffit pour toutes choses (réciter Al-Ikhlas et Al-Mu'awwidhatayn 3x matin et soir).",
        tr: "Her şeye karşı kafi gelir.",
        ur: "ہر چیز سے کافی ہو جاتا ہے۔",
      },
    },
    {
      id: 'morning_16',
      arabic: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ﴿١﴾ مِن شَرِّ مَا خَلَقَ ﴿٢﴾ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ﴿٣﴾ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ﴿٤﴾ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ ﴿٥﴾',
      transliteration: "Qul a'udhu birabbil-falaq. Min sharri ma khalaq. Wa min sharri ghasiqin idha waqab. Wa min sharrin-naffathati fil-'uqad. Wa min sharri hasidin idha hasad.",
      translations: {
        en: "Say: I seek refuge with the Lord of the Daybreak, from the evil of what He has created, from the evil of darkness when it settles, from the evil of those who blow on knots, and from the evil of an envier when he envies. (Surah Al-Falaq 113)",
        fr: "Dis: Je cherche refuge auprès du Seigneur de l'Aube naissante, contre le mal de ce qu'Il a créé, contre le mal de l'obscurité quand elle s'étend, contre le mal de celles qui soufflent sur les nœuds, et contre le mal de l'envieux quand il envie. (Sourate Al-Falaq 113)",
        tr: "De ki: Yarattığı şeylerin şerrinden, karanlığı çöktüğünde gecenin şerrinden, düğümlere üfleyenlerin şerrinden ve kıskandığında kıskancın şerrinden sabahın Rabbine sığınırım. (Felak Suresi 113)",
        ur: "کہو: میں پناہ لیتا ہوں طلوع صبح کے رب کی، ہر اس چیز کے شر سے جو اس نے پیدا کی، اندھیری رات کے شر سے جب وہ چھا جائے، گرہوں میں پھونکنے والیوں کے شر سے، اور حسد کرنے والے کے شر سے جب وہ حسد کرے۔ (سورة الفلق ١١٣)",
        id: "Katakanlah: Aku berlindung kepada Tuhan yang menguasai subuh, dari kejahatan makhluk-Nya, dari kejahatan malam apabila telah gelap gulita, dari kejahatan wanita-wanita tukang sihir yang menghembus pada buhul-buhul, dan dari kejahatan orang yang dengki apabila ia dengki. (Surah Al-Falaq 113)",
        ms: "Katakanlah: Aku berlindung dengan Tuhan yang mencetuskan fajar, dari kejahatan segala yang Dia ciptakan, dari kejahatan malam apabila ia gelap gelita, dari kejahatan mereka yang meniup pada simpulan-simpulan. (Surah Al-Falaq 113)",
        fa: "بگو: پناه می‌برم به پروردگار سپیده‌دم، از شر آنچه آفریده، از شر شب تاریک چون فرا رسد، از شر افسونگرانی که در گره‌ها می‌دمند، و از شر حسودی چون حسد ورزد. (سوره الفلق ١١٣)",
        bn: "বলুন: আমি আশ্রয় প্রার্থনা করছি উষার প্রভুর কাছে, তিনি যা সৃষ্টি করেছেন তার অনিষ্ট থেকে। (সূরা আল-ফালাক ১১৩)",
        zh: "说：我寻求晨光之主的庇护，免受祂所造之物的伤害。 (法莱格章 113)",
        ru: "Скажи: Прибегаю к защите Господа рассвета от зла того, что Он сотворил. (Сура Аль-Фалак 113)",
        es: "Di: Me refugio en el Señor del Amanecer, del mal de lo que ha creado. (Sura Al-Falaq 113)",
        pt: "Diga: Busco refúgio no Senhor do Amanhecer, do mal do que Ele criou. (Surah Al-Falaq 113)",
        sw: "Sema: Ninajikinga kwa Mola wa mapambazuko, na shari ya alichoviumba. (Sura Al-Falaq 113)",
        ha: "Ka ce: Ina neman tsari a wajen Ubangijin alfijir, daga sharrin abin da Ya halitta. (Surar Al-Falaq 113)",
      },
      count: 3,
      source: 'أبو داود ٥٠٨٢، النسائي ٥٤٢٨',
      sourceEn: 'Abu Dawud 5082, An-Nasai 5428',
      virtue: {
        ar: 'من قرأ المعوذتين حين يصبح وحين يمسي كفتاه من كل شيء',
        en: "Whoever recites Al-Mu'awwidhatayn in the morning and evening, they suffice for everything.",
        fr: "Quiconque récite Al-Mu'awwidhatayn le matin et le soir, elles lui suffisent pour tout.",
        tr: "Sabah ve akşam Muavvizeteyn'i okuyanın her şeyine kafi gelir.",
        ur: "جو صبح و شام معوذتین پڑھے وہ اسے ہر چیز کے لیے کافی ہو جاتی ہیں۔",
        id: "Barangsiapa membaca Al-Mu'awwidhatayn di pagi dan sore hari, keduanya mencukupinya dari segala sesuatu.",
      },
    },
    {
      id: 'morning_17',
      arabic: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ ﴿١﴾ مَلِكِ النَّاسِ ﴿٢﴾ إِلَٰهِ النَّاسِ ﴿٣﴾ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ﴿٤﴾ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ﴿٥﴾ مِنَ الْجِنَّةِ وَالنَّاسِ ﴿٦﴾',
      transliteration: "Qul a'udhu birabbin-nas. Malikin-nas. Ilahin-nas. Min sharril-waswasil-khannas. Alladhi yuwaswisu fi sudurin-nas. Minal-jinnati wan-nas.",
      translations: {
        en: "Say: I seek refuge with the Lord of mankind, the King of mankind, the God of mankind, from the evil of the sneaking whisperer, who whispers in the hearts of mankind, from among the jinn and mankind. (Surah An-Nas 114)",
        fr: "Dis: Je cherche refuge auprès du Seigneur des hommes, du Roi des hommes, du Dieu des hommes, contre le mal du tentateur sournois qui souffle le mal dans les cœurs des hommes, qu'il soit parmi les djinns ou parmi les hommes. (Sourate An-Nas 114)",
        tr: "De ki: İnsanların Rabbine, insanların Melikine, insanların İlahına sığınırım; sinsi vesvesecinin şerrinden; o ki insanların göğüslerine vesvese sokar; cinlerden de insanlardan da. (Nas Suresi 114)",
        ur: "کہو: میں پناہ لیتا ہوں لوگوں کے رب کی، لوگوں کے بادشاہ کی، لوگوں کے معبود کی، وسوسہ ڈالنے والے پیچھے ہٹ جانے والے کے شر سے، جو لوگوں کے دلوں میں وسوسہ ڈالتا ہے، جنوں میں سے بھی اور انسانوں میں سے بھی۔ (سورة الناس ١١٤)",
        id: "Katakanlah: Aku berlindung kepada Tuhan manusia, Raja manusia, Sesembahan manusia, dari kejahatan bisikan yang biasa bersembunyi, yang membisikkan kejahatan ke dalam dada manusia, dari golongan jin maupun manusia. (Surah An-Nas 114)",
        ms: "Katakanlah: Aku berlindung dengan Tuhan manusia, Raja manusia, Tuhan yang disembah oleh manusia, dari kejahatan pembisik yang suka bersembunyi, yang membisikkan kejahatan dalam dada manusia, dari kalangan jin mahupun manusia. (Surah An-Nas 114)",
        fa: "بگو: پناه می‌برم به پروردگار مردم، پادشاه مردم، معبود مردم، از شر وسواس‌گر پنهان‌شونده، که در سینه‌های مردم وسوسه می‌افکند، از جن و انس. (سوره الناس ١١٤)",
        bn: "বলুন: আমি মানুষের প্রভুর আশ্রয় চাই, মানুষের অধিপতির, মানুষের উপাস্যের কাছে। (সূরা আন-নাস ১১৪)",
        zh: "说：我寻求人类之主的庇护，人类之王，人类之神，免受喋喋不休的恶魔的伤害。 (人章 114)",
        ru: "Скажи: Прибегаю к защите Господа людей, Царя людей, Бога людей. (Сура Ан-Нас 114)",
        es: "Di: Me refugio en el Señor de la humanidad, el Rey de la humanidad, el Dios de la humanidad. (Sura An-Nas 114)",
        pt: "Diga: Busco refúgio no Senhor da humanidade, no Rei da humanidade, no Deus da humanidade. (Surah An-Nas 114)",
        sw: "Sema: Ninajikinga kwa Mola wa watu, Mfalme wa watu, Mungu wa watu. (Sura An-Nas 114)",
        ha: "Ka ce: Ina neman tsari a wajen Ubangijin mutane, Sarkin mutane, Ilahin mutane. (Surar An-Nas 114)",
      },
      count: 3,
      source: 'أبو داود ٥٠٨٢، النسائي ٥٤٢٨',
      sourceEn: 'Abu Dawud 5082, An-Nasai 5428',
    },
    {
      id: 'morning_01',
      arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذَا الْيَوْمِ وَخَيْرَ مَا بَعْدَهُ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ، رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ، رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ',
      transliteration: "Asbahna wa asbahal mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah, lahul mulku walahul hamdu wa huwa 'ala kulli shay'in qadir. Rabbi as'aluka khayra ma fi hadhal yawm wa khayra ma ba'dahu, wa a'udhu bika min sharri ma fi hadhal yawm wa sharri ma ba'dahu. Rabbi a'udhu bika minal kasali wa su'il kibar. Rabbi a'udhu bika min 'adhabin fin-nar wa 'adhabin fil-qabr.",
      translations: {
        en: "We have reached the morning and at this very time unto Allah belongs all sovereignty, and all praise is for Allah. None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and praise, and He is over all things omnipotent. My Lord, I ask You for the good of this day and the good of what follows it, and I take refuge in You from the evil of this day and the evil of what follows it. My Lord, I take refuge in You from laziness and the misery of old age. My Lord, I take refuge in You from torment in the Fire and punishment in the grave.",
        fr: "Nous voici au matin, et en ce moment toute la souveraineté appartient à Allah, toute la louange est à Allah. Nul n'a le droit d'être adoré sauf Allah, seul, sans associé. À Lui appartient toute souveraineté et toute louange, et Il est Omnipotent sur toute chose. Mon Seigneur, je Te demande le bien de cette journée et le bien de ce qui suit, et je cherche refuge auprès de Toi contre le mal de cette journée et le mal de ce qui suit.",
        tr: "Sabaha eriştik ve sabaha erdi mülk Allah'a aittir. Hamd Allah'a mahsustur. Allah'tan başka ilah yoktur, O tektir, ortağı yoktur. Mülk O'nundur, hamd O'nundur ve O her şeye kadirdir.",
        ur: "ہم نے صبح کی اور صبح کی ملک اللہ کے لیے، حمد اللہ کے لیے، اللہ کے سوا کوئی معبود نہیں، وہ اکیلا ہے، اس کا کوئی شریک نہیں۔",
        id: "Kami telah memasuki waktu pagi dan kerajaan hanya milik Allah, segala puji bagi Allah. Tiada Tuhan yang berhak disembah kecuali Allah semata, tiada sekutu bagi-Nya.",
        ms: "Kami telah memasuki waktu pagi, dan pada waktu ini kerajaan hanya milik Allah, segala puji bagi Allah.",
        bn: "আমরা সকালে উপনীত হলাম এবং সকালে আল্লাহর রাজত্ব হলো।",
        fa: "صبح کردیم و صبح کرد ملک برای خداوند و حمد برای خداوند است.",
      },
      count: 1,
      source: 'مسلم ٢٧٢٣',
      sourceEn: 'Muslim 2723',
    },
    {
      id: 'morning_02',
      arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ',
      transliteration: "Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namutu, wa ilaykan-nushur.",
      translations: {
        en: "O Allah, by Your leave we have reached the morning and by Your leave we have reached the evening, by Your leave we live and die and unto You is our resurrection.",
        fr: "Ô Allah, c'est grâce à Toi que nous avons atteint le matin, et c'est grâce à Toi que nous atteignons le soir, c'est grâce à Toi que nous vivons et mourons, et vers Toi est la résurrection.",
        tr: "Ey Allah'ım! Senin izninle sabaha eriştik, Senin izninle akşama eriştik, Seninle yaşar Seninle ölürüz ve dönüş Sanadır.",
        ur: "اے اللہ! تیری توفیق سے ہم نے صبح کی اور تیری توفیق سے شام کریں گے، تیرے ساتھ جیتے ہیں اور تیرے ساتھ مرتے ہیں، اور تیری طرف اٹھنا ہے۔",
        id: "Ya Allah, dengan-Mu kami memasuki waktu pagi, dan dengan-Mu kami memasuki waktu sore, dengan-Mu kami hidup, dengan-Mu kami mati, dan kepada-Mu tempat kembali.",
        ms: "Ya Allah, dengan-Mu kami melalui pagi hari, dengan-Mu kami melalui petang hari, dengan-Mu kami hidup dan mati, dan kepada-Mu kami akan dibangkitkan.",
        fa: "بارخدایا! به یاری تو وارد صبح شدیم و به یاری تو شب را سپری کردیم، با تو زندگی می‌کنیم و با تو می‌میریم و بازگشت به سوی توست.",
      },
      count: 1,
      source: 'أبو داود ٥٠٦٨، الترمذي ٣٣٩١',
      sourceEn: 'Abu Dawud 5068, Tirmidhi 3391',
    },
    {
      id: 'morning_03',
      arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
      transliteration: "Allahumma anta rabbi la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't, a'udhu bika min sharri ma sana't, abu'u laka bini'matika 'alayy, wa abu'u bidhanbi faghfir li fa innahu la yaghfirudh-dhunuba illa ant.",
      translations: {
        en: "O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I abide to Your covenant and promise as best I can. I take refuge in You from the evil of which I have committed. I acknowledge Your favour upon me and I acknowledge my sin, so forgive me, for verily none can forgive sin except You.",
        fr: "Ô Allah, Tu es mon Seigneur, nul n'a le droit d'être adoré sauf Toi. Tu m'as créé et je suis Ton serviteur. Je m'attiens à Ton alliance et à Ta promesse autant que je peux. Je cherche refuge auprès de Toi contre le mal de ce que j'ai commis. Je reconnais Tes bienfaits sur moi et je reconnais mes péchés, alors pardonne-moi car nul ne pardonne les péchés sauf Toi.",
        tr: "Allah'ım! Sen benim Rabbimsin, Senden başka ilah yoktur. Sen beni yarattın, ben Senin kulunum. Gücüm yettiğince Sana verdiğim sözü ve ahdimi yerine getirmeye çalışıyorum.",
        ur: "اے اللہ! تو میرا رب ہے، تیرے سوا کوئی معبود نہیں۔ تو نے مجھے پیدا کیا اور میں تیرا بندہ ہوں، اپنی استطاعت کے مطابق تیرے عہد و پیمان پر قائم ہوں۔",
        id: "Ya Allah, Engkau adalah Tuhanku, tidak ada Tuhan yang berhak disembah kecuali Engkau. Engkau telah menciptakanku dan aku adalah hamba-Mu.",
        ms: "Ya Allah, Engkaulah Tuhanku, tiada tuhan selain-Mu. Engkau menciptakanku dan aku adalah hamba-Mu.",
        fa: "بارخدایا! تو پروردگار من هستی، جز تو معبودی نیست. مرا آفریدی و من بنده تو هستم.",
      },
      count: 1,
      source: 'البخاري ٦٣٠٦',
      sourceEn: 'Bukhari 6306',
      virtue: {
        ar: 'من قالها موقناً بها فمات من يومه قبل أن يمسي فهو من أهل الجنة',
        en: 'Whoever says it with certainty and dies that day before evening, they are among the people of Paradise.',
        fr: "Quiconque le dit avec certitude et meurt ce jour-là avant le soir, il fait partie des gens du Paradis.",
        tr: "Kim buna inanarak söyler de o günün akşamına ulaşmadan ölürse, Cennet ehlinden olur.",
        ur: "جو اسے یقین کے ساتھ پڑھے اور اس دن شام سے پہلے مر جائے تو وہ جنتیوں میں سے ہے۔",
        id: "Barangsiapa mengucapkannya dengan yakin kemudian meninggal di hari itu sebelum sore hari, maka ia termasuk ahli surga.",
      },
    },
    {
      id: 'morning_04',
      arabic: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلَهَ إِلَّا أَنْتَ',
      transliteration: "Allahumma 'afini fi badani, Allahumma 'afini fi sam'i, Allahumma 'afini fi basari, la ilaha illa ant.",
      translations: {
        en: "O Allah, grant my body health. O Allah, grant my hearing health. O Allah, grant my sight health. None has the right to be worshipped except You.",
        fr: "Ô Allah, accorde la santé à mon corps. Ô Allah, accorde la santé à mon ouïe. Ô Allah, accorde la santé à ma vue. Nul n'a le droit d'être adoré sauf Toi.",
        tr: "Allah'ım! Bedenime afiyet ver, Allah'ım! Kulağıma afiyet ver, Allah'ım! Gözüme afiyet ver. Senden başka ilah yoktur.",
        ur: "اے اللہ! میرے جسم کو عافیت دے، اے اللہ! میری سماعت کو عافیت دے، اے اللہ! میری بصارت کو عافیت دے۔ تیرے سوا کوئی معبود نہیں۔",
        id: "Ya Allah, berilah kesehatan pada tubuhku. Ya Allah, berilah kesehatan pada pendengaranku. Ya Allah, berilah kesehatan pada penglihatanku. Tiada Tuhan selain Engkau.",
        ms: "Ya Allah, kurniakanlah kesihatan pada badanku. Ya Allah, kurniakanlah kesihatan pada pendengaranku. Ya Allah, kurniakanlah kesihatan pada penglihatanku.",
        fa: "خدایا! به تن من عافیت بده، خدایا! به شنوایی من عافیت بده، خدایا! به بینایی من عافیت بده، جز تو معبودی نیست.",
      },
      count: 3,
      source: 'أبو داود ٥٠٩٠',
      sourceEn: 'Abu Dawud 5090',
    },
    {
      id: 'morning_05',
      arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
      transliteration: "Bismillahil-ladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'i wa huwas-sami'ul-'alim.",
      translations: {
        en: "In the name of Allah with whose name nothing is harmed on earth nor in the heavens, and He is the All-Seeing, the All-Knowing.",
        fr: "Au nom d'Allah, par le nom duquel rien ne peut nuire sur la terre ni dans les cieux, et Il est le Tout-Entendant, l'Omniscient.",
        tr: "Allah'ın adıyla, Yerde ve gökte O'nun adıyla hiçbir şey zarar vermez. O işitendir, bilendir.",
        ur: "اللہ کے نام سے جس کے نام کے ساتھ زمین و آسمان میں کوئی چیز نقصان نہیں پہنچاتی، وہ سمیع و علیم ہے۔",
        id: "Dengan nama Allah yang dengan nama-Nya tidak ada sesuatu pun yang membahayakan di bumi maupun di langit, dan Dia Maha Mendengar lagi Maha Mengetahui.",
        ms: "Dengan nama Allah yang dengan nama-Nya tidak ada sesuatu yang membahayakan di bumi dan di langit, dan Dialah Yang Maha Mendengar lagi Maha Mengetahui.",
        fa: "به نام خداوندی که با نام او هیچ چیزی در زمین و آسمان زیان نمی‌رساند و اوست شنوای دانا.",
      },
      count: 3,
      source: 'أبو داود ٥٠٨٨، الترمذي ٣٣٨٨',
      sourceEn: 'Abu Dawud 5088, Tirmidhi 3388',
      virtue: {
        ar: 'لم يضره شيء',
        en: 'Nothing shall harm them.',
        fr: "Rien ne lui nuira.",
        tr: "Hiçbir şey ona zarar veremez.",
        ur: "اسے کوئی چیز نقصان نہیں پہنچائے گی۔",
        id: "Tidak ada sesuatu pun yang dapat membahayakannya.",
      },
    },
    {
      id: 'morning_06',
      arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا',
      transliteration: "Raditu billahi rabban, wa bil-islami dinan, wa bi-muhammadin sallallahu 'alayhi wa sallam nabiyya.",
      translations: {
        en: "I am pleased with Allah as my Lord, with Islam as my religion and with Muhammad (peace be upon him) as my Prophet.",
        fr: "Je suis satisfait d'Allah comme Seigneur, de l'Islam comme religion et de Muhammad (que la paix soit sur lui) comme prophète.",
        tr: "Allah'ı Rab, İslam'ı din, Hz. Muhammed'i (s.a.v.) peygamber olarak kabul etmekten razıyım.",
        ur: "میں اللہ کے رب ہونے، اسلام کے دین ہونے اور محمد ﷺ کے نبی ہونے پر راضی ہوں۔",
        id: "Aku rela Allah sebagai Tuhanku, Islam sebagai agamaku dan Muhammad shallallahu 'alaihi wa sallam sebagai nabiku.",
        ms: "Aku redha dengan Allah sebagai Tuhanku, Islam sebagai agamaku dan Muhammad S.A.W sebagai nabiku.",
        fa: "به خداوند به عنوان پروردگار، به اسلام به عنوان دین و به محمد صلی الله علیه وسلم به عنوان پیامبر راضی هستم.",
      },
      count: 3,
      source: 'أبو داود ٥٠٧٢',
      sourceEn: 'Abu Dawud 5072',
      virtue: {
        ar: 'كان حقاً على الله أن يرضيه يوم القيامة',
        en: 'It will be right upon Allah to please them on the Day of Resurrection.',
        fr: "Il sera du droit sur Allah de les satisfaire le Jour du Jugement.",
        tr: "Allah'ın kıyamet günü onu razı etmesi hak olur.",
        ur: "اللہ پر حق ہو جاتا ہے کہ قیامت کے دن اسے راضی کرے۔",
      },
    },
    {
      id: 'morning_07',
      arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ',
      transliteration: "Ya Hayyu ya Qayyumu birahmatika astaghith, aslih li sha'ni kullahu, wa la takilni ila nafsi tarfata 'ayn.",
      translations: {
        en: "O Ever-Living, O Self-Subsisting and Supporter of all, by Your mercy I seek relief. Rectify all my affairs and do not leave me to myself, even for the blink of an eye.",
        fr: "Ô Vivant, Ô Subsistant par Lui-même! C'est par Ta miséricorde que j'implore Ton aide. Arrange-moi toutes mes affaires et ne me laisse pas à moi-même, ne serait-ce que le temps d'un clin d'œil.",
        tr: "Ey Hay, ey Kayyum! Rahmetinle senden yardım diliyorum. Bütün işlerimi düzelt ve beni bir göz kırpması kadar bile nefsimle başbaşa bırakma.",
        ur: "اے حی! اے قیوم! تیری رحمت کے وسیلے سے فریاد کرتا ہوں، میرے تمام معاملات درست فرما دے اور ایک پل کے لیے بھی مجھے میرے نفس کے حوالے نہ کر۔",
        id: "Wahai Yang Maha Hidup, wahai Yang Maha Berdiri sendiri, dengan rahmat-Mu aku memohon pertolongan. Perbaikilah seluruh urusanku dan janganlah Engkau serahkan aku kepada diriku sendiri walau sekejap mata.",
        ms: "Wahai Yang Maha Hidup, Wahai Yang Maha Berdiri Sendiri! Dengan rahmat-Mu aku memohon pertolongan. Perbaikilah semua urusanku dan janganlah Engkau serahkan aku kepada diriku sendiri walau sekelip mata.",
        fa: "ای زنده پاینده! به رحمتت پناه می‌برم، تمام کارهایم را اصلاح کن و مرا حتی به اندازه یک چشم برهم زدن به خودم وامگذار.",
      },
      count: 3,
      source: 'النسائي في الكبرى ٩٨٣٨، صحيح الجامع ٧٩٩٥',
      sourceEn: "An-Nasa'i (Al-Kubra) 9838, Sahih al-Jami' 7995",
    },
    {
      id: 'morning_08',
      arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
      transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq.",
      translations: {
        en: "I take refuge in the Perfect Words of Allah from the evil of what He has created.",
        fr: "Je cherche refuge auprès des Paroles parfaites d'Allah contre le mal de ce qu'Il a créé.",
        tr: "Allah'ın yarattıklarının şerrinden O'nun eksiksiz kelimelerine sığınırım.",
        ur: "اللہ کے کامل کلمات کی پناہ لیتا ہوں ان تمام مخلوقات کے شر سے جو اس نے پیدا کی ہیں۔",
        id: "Aku berlindung dengan kalimat-kalimat Allah yang sempurna dari kejahatan makhluk yang Allah ciptakan.",
        ms: "Aku berlindung dengan kalimat-kalimat Allah yang sempurna daripada kejahatan apa yang telah Dia ciptakan.",
        fa: "پناه می‌برم به کلمات کامل الهی از شر آنچه آفریده است.",
      },
      count: 3,
      source: 'مسلم ٢٧٠٩',
      sourceEn: 'Muslim 2709',
    },
    {
      id: 'morning_09',
      arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالآخِرَةِ، اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي',
      transliteration: "Allahumma inni as'alukal-'afwa wal-'afiyah fid-dunya wal-akhirah. Allahumma inni as'alukal-'afwa wal-'afiyah fi dini wa dunya-ya wa ahli wa mali.",
      translations: {
        en: "O Allah, I ask You for pardon and well-being in this life and the next. O Allah, I ask You for pardon and well-being in my religious and worldly affairs, and my family and my wealth.",
        fr: "Ô Allah, je Te demande le pardon et le bien-être dans ce monde et dans l'au-delà. Ô Allah, je Te demande le pardon et le bien-être dans ma religion, ma vie terrestre, ma famille et mes biens.",
        tr: "Allah'ım! Senden dünya ve ahirette af ve afiyet istiyorum. Allah'ım! Dinim, dünyam, ailem ve malım için af ve afiyet istiyorum.",
        ur: "اے اللہ! دنیا اور آخرت میں عفو و عافیت مانگتا ہوں۔ اے اللہ! اپنے دین، دنیا، اہل و عیال اور مال میں عفو و عافیت مانگتا ہوں۔",
        id: "Ya Allah, aku memohon kepada-Mu maaf dan keselamatan di dunia dan akhirat. Ya Allah, aku memohon kepada-Mu maaf dan keselamatan dalam agamaku, duniaku, keluargaku dan hartaku.",
        ms: "Ya Allah, aku memohon keampunan dan keselamatan di dunia dan akhirat. Ya Allah, aku memohon keampunan dan keselamatan dalam agama, dunia, keluarga dan hartaku.",
        fa: "خدایا! در دنیا و آخرت از تو عفو و عافیت می‌خواهم. خدایا! در دین و دنیا و خانواده و مالم از تو عفو و عافیت می‌خواهم.",
      },
      count: 1,
      source: 'أبو داود ٥٠٧٤، ابن ماجه ٣٨٧١',
      sourceEn: 'Abu Dawud 5074, Ibn Majah 3871',
    },
    {
      id: 'morning_10',
      arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا',
      transliteration: "Allahumma inni as'aluka 'ilman nafi'an, wa rizqan tayyiban, wa 'amalan mutaqabbala.",
      translations: {
        en: "O Allah, I ask You for knowledge that is of benefit, a good provision and deeds that will be accepted.",
        fr: "Ô Allah, je Te demande une connaissance utile, une bonne subsistance et des actes acceptés.",
        tr: "Allah'ım! Faydalı ilim, helal rızık ve makbul amel istiyorum.",
        ur: "اے اللہ! نفع بخش علم، پاکیزہ رزق اور مقبول عمل کا سوالی ہوں۔",
        id: "Ya Allah, aku memohon kepada-Mu ilmu yang bermanfaat, rezeki yang baik, dan amal yang diterima.",
        ms: "Ya Allah, aku memohon kepada-Mu ilmu yang bermanfaat, rezeki yang baik dan amalan yang diterima.",
        fa: "خدایا! دانش سودمند، روزی پاک و عمل مقبول از تو می‌خواهم.",
      },
      count: 1,
      source: 'ابن ماجه ٩٢٥، صحيح',
      sourceEn: 'Ibn Majah 925, Sahih',
    },
    {
      id: 'morning_11',
      arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
      transliteration: "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadir.",
      translations: {
        en: "None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and praise, and He is over all things omnipotent.",
        fr: "Nul n'a le droit d'être adoré sauf Allah, seul, sans associé. À Lui appartient toute souveraineté et toute louange, et Il est Omnipotent sur toute chose.",
        tr: "Allah'tan başka ilah yoktur. O tektir, ortağı yoktur. Mülk O'nundur, hamd O'nundur ve O her şeye kadirdir.",
        ur: "اللہ کے سوا کوئی معبود نہیں، وہ اکیلا ہے، اس کا کوئی شریک نہیں، ملک اسی کا ہے، حمد اسی کے لیے ہے اور وہ ہر چیز پر قادر ہے۔",
        id: "Tidak ada tuhan yang berhak disembah selain Allah semata, tidak ada sekutu bagi-Nya. Bagi-Nya kerajaan dan bagi-Nya segala pujian. Dan Dia Maha Kuasa atas segala sesuatu.",
        ms: "Tiada tuhan selain Allah semata-mata, tiada sekutu bagi-Nya. Bagi-Nya kerajaan dan bagi-Nya segala puji. Dia Maha Berkuasa atas segala sesuatu.",
        fa: "هیچ معبودی جز الله نیست، یگانه‌ای بی‌شریک، ملک از اوست و حمد از اوست و او بر هر چیزی توانا است.",
      },
      count: 100,
      source: 'البخاري ٦٤٠٤، مسلم ٢٦٩٢',
      sourceEn: 'Bukhari 6404, Muslim 2692',
      virtue: {
        ar: 'كتب له مئة حسنة ومحيت عنه مئة سيئة وكانت له حرزاً من الشيطان يومه ذلك',
        en: 'One hundred good deeds are written for them, one hundred bad deeds are wiped away, and it is a shield against Shaytan that day.',
        fr: "Cent bonnes actions lui sont inscrites, cent mauvaises actions lui sont effacées, et c'est une protection contre Shaytan pour ce jour-là.",
        tr: "Yüz sevap yazılır, yüz günah silinir ve o gün şeytana karşı kalkan olur.",
        ur: "سو نیکیاں لکھی جاتی ہیں، سو برائیاں مٹا دی جاتی ہیں اور اس دن شیطان سے حفاظت ہوتی ہے۔",
      },
    },
    {
      id: 'morning_12',
      arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
      transliteration: "Subhanallahi wa bihamdih.",
      translations: {
        en: "Glory be to Allah and praise be to Him.",
        fr: "Gloire à Allah et que la louange Lui soit rendue.",
        tr: "Allah'ı tüm noksan sıfatlardan tenzih eder ve O'na hamdederim.",
        ur: "اللہ پاک ہے اور اس کی حمد کے ساتھ۔",
        id: "Maha Suci Allah dan segala puji bagi-Nya.",
        ms: "Maha Suci Allah dan segala puji bagi-Nya.",
        fa: "خداوند منزه است و ستایش او را می‌گویم.",
        bn: "আল্লাহ পবিত্র এবং তাঁর প্রশংসা।",
        sw: "Utukufu ni wa Allah na sifa zote ni zake.",
        ha: "Allah ya kebe kuma godiya tana gare Shi.",
        zh: "赞美真主，并感谢他。",
        ru: "Слава Аллаху и хвала Ему.",
        es: "Gloria sea a Alá y toda la alabanza es para Él.",
        pt: "Glória a Allah e Louvor a Ele.",
      },
      count: 100,
      source: 'البخاري ٦٤٠٥، مسلم ٢٦٩١',
      sourceEn: 'Bukhari 6405, Muslim 2691',
      virtue: {
        ar: 'من قالها مئة مرة حطت خطاياه وإن كانت مثل زبد البحر',
        en: "Whoever says it 100 times, their sins are forgiven even if they were like the foam of the sea.",
        fr: "Quiconque le dit cent fois, ses péchés lui sont pardonnés même s'ils étaient comme l'écume de la mer.",
        tr: "Kim günde yüz kez söylerse, günahları denizin köpüğü kadar olsa bile silinir.",
        ur: "جو سو مرتبہ پڑھے اس کے گناہ معاف کر دیے جاتے ہیں خواہ سمندر کی جھاگ کے برابر ہوں۔",
      },
    },
    {
      id: 'morning_13',
      arabic: 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ',
      transliteration: "Allahumma salli wa sallim 'ala nabiyyina Muhammad.",
      translations: {
        en: "O Allah, send peace and blessings upon our Prophet Muhammad.",
        fr: "Ô Allah, envoie Ta grâce et Ta paix sur notre Prophète Mohammed.",
        tr: "Allah'ım! Peygamberimiz Muhammed'e salât ve selam eyle.",
        ur: "اے اللہ! ہمارے نبی محمد ﷺ پر درود و سلام نازل فرما۔",
        id: "Ya Allah, limpahkanlah shalawat dan salam kepada Nabi kami Muhammad.",
        ms: "Ya Allah, selawat dan salam ke atas Nabi kami Muhammad.",
        fa: "خدایا! بر پیامبرمان محمد درود و سلام بفرست.",
        bn: "হে আল্লাহ! আমাদের নবী মুহাম্মদের উপর দরুদ ও সালাম পাঠাও।",
        zh: "愿安拉赐福我们的先知穆罕默德。",
        ru: "О Аллах, благослови нашего Пророка Мухаммада и приветствуй его.",
        es: "Oh Allah, envía bendiciones y paz sobre nuestro Profeta Muhammad.",
        pt: "Oh Allah, envia bênçãos e paz sobre o nosso Profeta Muhammad.",
        sw: "Ewe Mwenyezi Mungu, mtumie rehema na amani Mtume wetu Muhammad.",
        ha: "Ya Allah, ka yi salati da sallama a kan annabinmu Muhammadu.",
      },
      count: 10,
      source: 'الطبراني، صحيح الجامع ٦٣٥٧',
      sourceEn: "Al-Tabarani, Sahih al-Jami' 6357",
      virtue: {
        ar: 'من صلى علي صلاة صلى الله عليه بها عشراً',
        en: 'Whoever sends one blessing upon me, Allah sends ten blessings upon them.',
        fr: "Quiconque m'envoie une prière, Allah lui en envoie dix.",
        tr: "Kim bana bir salat getirirse, Allah ona on salat getirir.",
        ur: "جو مجھ پر ایک بار درود بھیجے اللہ اس پر دس رحمتیں نازل فرماتا ہے۔",
      },
    },
    {
      id: 'morning_18',
      arabic: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
      transliteration: "Hasbiyallahu la ilaha illa huwa 'alayhi tawakkaltu wa huwa rabbul-'arshil-'azim.",
      translations: {
        en: "Allah is sufficient for me. There is no god but He. In Him I put my trust, and He is the Lord of the Mighty Throne.",
        fr: "Allah me suffit. Il n'y a point de divinité sauf Lui. En Lui je place ma confiance, et Il est le Seigneur du Trône immense.",
        tr: "Allah bana yeter. O'ndan başka ilah yoktur. O'na tevekkül ettim. O, büyük Arş'ın Rabbidir.",
        ur: "اللہ مجھے کافی ہے، اس کے سوا کوئی معبود نہیں، میں نے اسی پر بھروسہ کیا اور وہ عرش عظیم کا رب ہے۔",
        id: "Cukuplah Allah bagiku. Tidak ada tuhan selain Dia. Kepada-Nya aku bertawakkal dan Dia adalah Tuhan Arsy yang agung.",
        ms: "Cukuplah Allah bagiku. Tiada tuhan selain-Nya. Kepada-Nya aku bertawakkal dan Dia adalah Tuhan Arasy yang agung.",
        fa: "خداوند برایم کافی است. جز او معبودی نیست. بر او توکل کردم و او پروردگار عرش بزرگ است.",
        bn: "আল্লাহই আমার জন্য যথেষ্ট। তিনি ছাড়া কোনো উপাস্য নেই। তাঁর উপরই আমি ভরসা করি।",
        zh: "真主对我来说就足够了。除祂外别无神。我信赖祂，祂是伟大宝座的主。",
        ru: "Мне достаточно Аллаха. Нет бога, кроме Него. На Него я уповаю.",
        es: "Allah me es suficiente. No hay dios excepto Él. En Él confío y Él es el Señor del Trono Inmenso.",
        pt: "Allah é suficiente para mim. Não há deus exceto Ele. Nele deposito minha confiança.",
        sw: "Allah yanitosha. Hapana Mungu ila Yeye. Kwake ninategemea.",
        ha: "Allah ya ishe ni. Babu abin bautawa sai Shi. A kansa na dogara.",
      },
      count: 7,
      source: 'أبو داود ٥٠٨١، صحيح',
      sourceEn: 'Abu Dawud 5081, Sahih',
      virtue: {
        ar: 'من قالها سبع مرات حين يصبح وحين يمسي كفاه الله ما أهمه من أمر الدنيا والآخرة',
        en: 'Whoever says it seven times morning and evening, Allah will spare them whatever worries them of worldly and religious affairs.',
        fr: "Quiconque la dit sept fois le matin et le soir, Allah lui suffira dans ce qui l'inquiète.",
        tr: "Kim sabah akşam yedi kez söylerse Allah dünya ve ahiret işlerinde onu endişelendiren şeylerde ona yeter.",
        ur: "جو صبح و شام سات بار پڑھے اللہ اسے دنیا و آخرت کے معاملات میں کافی ہو جاتا ہے۔",
        id: "Barangsiapa mengucapkannya tujuh kali pagi dan sore, Allah akan mencukupinya dari segala yang mengkhawatirkannya.",
      },
    },
    {
      id: 'morning_19',
      arabic: 'اللَّهُمَّ إِنِّي أَصْبَحْتُ أُشْهِدُكَ وَأُشْهِدُ حَمَلَةَ عَرْشِكَ وَمَلَائِكَتَكَ وَجَمِيعَ خَلْقِكَ، أَنَّكَ أَنْتَ اللَّهُ لَا إِلَهَ إِلَّا أَنْتَ وَحْدَكَ لَا شَرِيكَ لَكَ، وَأَنَّ مُحَمَّدًا عَبْدُكَ وَرَسُولُكَ',
      transliteration: "Allahumma inni asbahtu ushhiduka wa ushhidu hamalata 'arshika wa mala'ikataka wa jami'a khalqika, annaka antallahu la ilaha illa anta wahdaka la sharika lak, wa anna muhammadan 'abduka wa rasuluk.",
      translations: {
        en: "O Allah, I have reached the morning and call upon You to witness, and I call upon the bearers of Your Throne, Your angels, and all of Your creation to witness, that You are Allah, none has the right to be worshipped except You, alone, without partner, and that Muhammad is Your servant and messenger.",
        fr: "Ô Allah, je suis parvenu au matin et je Te prends à témoin, et je prends à témoin les porteurs de Ton Trône, Tes anges, et toute Ta création, que Tu es Allah, nul n'a le droit d'être adoré sauf Toi, seul, sans associé, et que Muhammad est Ton serviteur et messager.",
        tr: "Allah'ım! Sabahladım. Seni, Arş'ını taşıyanları, meleklerini ve bütün yaratıklarını şahit tutuyorum ki Sen Allah'sın, Senden başka ilah yoktur, tek ve ortaksızsın, Muhammed Senin kulun ve elçindir.",
        ur: "اے اللہ! میں نے صبح کی، میں تجھے، تیرے عرش اٹھانے والوں، فرشتوں اور تمام مخلوق کو گواہ بناتا ہوں کہ تو اللہ ہے، تیرے سوا کوئی معبود نہیں، تو اکیلا ہے، کوئی شریک نہیں، اور محمد ﷺ تیرے بندے اور رسول ہیں۔",
        id: "Ya Allah, aku memasuki waktu pagi dengan menjadikan-Mu sebagai saksi, juga para malaikat pemikul Arsy-Mu, para malaikat-Mu, dan seluruh makhluk-Mu, bahwa sesungguhnya Engkau adalah Allah, tiada Tuhan selain Engkau semata, tiada sekutu bagi-Mu, dan bahwa Muhammad adalah hamba dan utusan-Mu.",
        ms: "Ya Allah, aku telah memasuki waktu pagi sambil menjadikan-Mu sebagai saksi dan juga para malaikat pemikul Arasy-Mu, para malaikat-Mu dan semua makhluk-Mu.",
        fa: "خدایا! صبح کردم و تو و حاملان عرشت و فرشتگانت و همه مخلوقاتت را گواه می‌گیرم که تو خداوندی هستی که جز تو معبودی نیست.",
        bn: "হে আল্লাহ! আমি সকালে উপনীত হলাম এবং তোমাকে, তোমার আরশ বহনকারীদের, তোমার ফেরেশতাদের এবং তোমার সকল সৃষ্টিকে সাক্ষী রাখছি।",
        zh: "主啊，我已迎来清晨，我请求你作证，也请求你的宝座的承担者、你的天使和你所有的造物作证。",
        ru: "О Аллах, я встретил утро и призываю Тебя в свидетели, и призываю носителей Твоего Трона, Твоих ангелов и все Твои творения в свидетели.",
        es: "Oh Allah, he llegado a la mañana y Te llamo como testigo, y llamo a los portadores de Tu Trono, a Tus ángeles y a todas Tus criaturas como testigos.",
        pt: "Ó Allah, cheguei à manhã e Te chamo como testemunha, e chamo os portadores do Teu Trono, os Teus anjos e todas as Tuas criaturas como testemunhas.",
        sw: "Ewe Mwenyezi Mungu, nimefika asubuhi nikikufanya ushuhuda, na kuwafanya ushuhuda wabeba Arshi yako.",
        ha: "Ya Allah, na safka safe ina shaida ka, kuma ina shaida masu daukan Arshinka da mala'ikunku da dukkan halittarka.",
      },
      count: 4,
      source: 'أبو داود ٥٠٨٣، صحيح',
      sourceEn: 'Abu Dawud 5083, Sahih',
      virtue: {
        ar: 'أعتقه الله من النار',
        en: 'Allah will free them from the Fire.',
        fr: "Allah les affranchira du Feu.",
        tr: "Allah onu ateşten azad eder.",
        ur: "اللہ اسے جہنم سے آزاد کر دے گا۔",
        id: "Allah akan membebaskannya dari api neraka.",
      },
    },
    {
      id: 'morning_20',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، لَا إِلَهَ إِلَّا أَنْتَ',
      transliteration: "Allahumma inni a'udhu bika minal-kufri wal-faqr, wa a'udhu bika min 'adhabil-qabr, la ilaha illa ant.",
      translations: {
        en: "O Allah, I seek refuge in You from disbelief and poverty, and I seek refuge in You from the punishment of the grave. None has the right to be worshipped except You.",
        fr: "Ô Allah, je cherche refuge auprès de Toi contre la mécréance et la pauvreté, et je cherche refuge auprès de Toi contre le châtiment de la tombe.",
        tr: "Allah'ım! Küfürden ve fakirlikten Sana sığınırım, kabir azabından da Sana sığınırım. Senden başka ilah yoktur.",
        ur: "اے اللہ! میں کفر اور فقر سے تیری پناہ مانگتا ہوں، اور عذاب قبر سے تیری پناہ مانگتا ہوں۔ تیرے سوا کوئی معبود نہیں۔",
        id: "Ya Allah, aku berlindung kepada-Mu dari kekufuran dan kefakiran, dan aku berlindung kepada-Mu dari azab kubur.",
        ms: "Ya Allah, aku berlindung kepada-Mu daripada kekufuran dan kemiskinan, dan aku berlindung kepada-Mu daripada azab kubur.",
        fa: "خدایا! از کفر و فقر به تو پناه می‌برم، و از عذاب قبر به تو پناه می‌برم.",
        bn: "হে আল্লাহ! আমি কুফর ও দারিদ্র্য থেকে তোমার আশ্রয় চাই, এবং কবরের আযাব থেকে তোমার আশ্রয় চাই।",
        zh: "主啊，我向你寻求庇护，免遭不信和贫困，我向你寻求庇护，免受墓中之苦。",
        ru: "О Аллах, я прибегаю к Тебе от неверия и бедности, и прибегаю к Тебе от мучений в могиле.",
        es: "Oh Allah, me refugio en Ti del descreer y de la pobreza, y me refugio en Ti del castigo de la tumba.",
        pt: "Ó Allah, refugio-me em Ti da descrença e da pobreza, e refugio-me em Ti do castigo do túmulo.",
        sw: "Ewe Mwenyezi Mungu, ninakukimbilia kutokana na ukafiri na umasikini, na azabu ya kaburi.",
        ha: "Ya Allah, ina neman tsarinKa daga kafirci da talauci, da azabar kabari.",
      },
      count: 3,
      source: 'أبو داود ٥٠٩٠، صحيح',
      sourceEn: 'Abu Dawud 5090, Sahih',
    },
    {
      id: 'morning_21',
      arabic: 'أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ',
      transliteration: "Astaghfirullaha wa atubu ilayh.",
      translations: {
        en: "I seek the forgiveness of Allah and I repent to Him.",
        fr: "Je demande pardon à Allah et je me repens à Lui.",
        tr: "Allah'tan bağışlanma diler ve O'na tövbe ederim.",
        ur: "میں اللہ سے مغفرت مانگتا ہوں اور اس کی طرف توبہ کرتا ہوں۔",
        id: "Aku memohon ampun kepada Allah dan bertaubat kepada-Nya.",
        ms: "Aku memohon keampunan Allah dan bertaubat kepada-Nya.",
        fa: "از خداوند آمرزش می‌طلبم و به سوی او توبه می‌کنم.",
        bn: "আমি আল্লাহর কাছে ক্ষমা প্রার্থনা করি এবং তাঁর দিকে তওবা করি।",
        zh: "我向真主祈求宽恕并向祂悔罪。",
        ru: "Я прошу у Аллаха прощения и каюсь перед Ним.",
        es: "Pido perdón a Allah y me arrepiento ante Él.",
        pt: "Peço perdão a Allah e me arrependo para Ele.",
        sw: "Ninamwomba Allah msamaha na ninageuka kwake.",
        ha: "Ina neman gafara daga Allah kuma ina tuba gare Shi.",
      },
      count: 100,
      source: 'البخاري ٦٣٠٧، مسلم ٢٧٠٢',
      sourceEn: 'Bukhari 6307, Muslim 2702',
      virtue: {
        ar: 'كان النبي ﷺ يستغفر الله في اليوم أكثر من سبعين مرة',
        en: 'The Prophet ﷺ used to seek forgiveness from Allah more than seventy times a day.',
        fr: "Le Prophète ﷺ demandait pardon à Allah plus de soixante-dix fois par jour.",
        tr: "Peygamber ﷺ günde yetmişten fazla istiğfar ederdi.",
        ur: "نبی ﷺ ایک دن میں ستر سے زیادہ بار اللہ سے استغفار فرماتے تھے۔",
        id: "Nabi ﷺ biasa memohon ampun kepada Allah lebih dari tujuh puluh kali sehari.",
      },
    },
  ],

  evening: [
    {
      id: 'evening_15',
      arabic: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ\n﴿اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ﴾',
      transliteration: "A'udhu billahi minash-shaytanir-rajim. Allahu la ilaha illa huwal-hayyul-qayyum, la ta'khudhuhu sinatun wa la nawm, lahu ma fis-samawati wa ma fil-ard, man dhal-ladhi yashfa'u 'indahu illa bi'idhnin, ya'lamu ma bayna aydihim wa ma khalfahum wa la yuhituna bishay'in min 'ilmihi illa bima sha', wasi'a kursiyyuhus-samawati wal-ard, wa la ya'uduhu hifzuhuma wa huwal-'aliyyul-'azim.",
      translations: {
        en: "Allah! None has the right to be worshipped but He, the Ever-Living, the One Who sustains and protects all that exists. Neither slumber nor sleep overtakes Him. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His throne extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great. (Ayat al-Kursi, Al-Baqarah 2:255)",
        fr: "Allah! Point de divinité à part Lui, le Vivant, Celui qui subsiste par lui-même. Ni la somnolence ni le sommeil ne Le saisissent. À Lui appartient tout ce qui est dans les cieux et sur la terre. Qui peut intercéder auprès de Lui sans Sa permission? (Verset du Trône, Al-Baqarah 2:255)",
        tr: "Allah, O'ndan başka tanrı yoktur. O, daima diri ve daima yarattıklarını gözetip durandır. Onu ne bir uyuklama ne de uyku yakalar. (Ayetel Kürsi, Bakara 2/255)",
        ur: "اللہ، اس کے سوا کوئی معبود نہیں، وہ ہمیشہ زندہ اور قائم رہنے والا ہے، اسے نہ اونگھ آتی ہے نہ نیند۔ (آیة الکرسی، البقرة ٢:٢٥٥)",
        id: "Allah, tidak ada Tuhan selain Dia. Yang Maha Hidup, yang terus-menerus mengurus makhluk-Nya. Tidak mengantuk dan tidak tidur. (Ayat Al-Kursi, Al-Baqarah 2:255)",
        ms: "Allah, tiada Tuhan selain-Nya, Yang Maha Hidup, Yang Terus menerus mengurus makhluk-Nya. (Ayat al-Kursi, Al-Baqarah 2:255)",
        fa: "خداوند، هیچ معبودی جز او نیست، زنده‌ای پاینده است. (آیةالکرسی، البقره ۲:۲۵۵)",
        bn: "আল্লাহ, তিনি ছাড়া কোনো উপাস্য নেই, চিরজীবী, সর্বসত্তার ধারক। (আয়াতুল কুরসি, আল-বাকারা ২:২৫৫)",
        zh: "真主，除祂外，绝无应受崇拜的，祂是永生的，是维护万物的。 (宝座节，牧牛章 2:255)",
        ru: "Аллах — нет божества, кроме Него, Живого, Вечносущего. Его не постигают ни дремота, ни сон. (Аят аль-Курси, Аль-Бакара 2:255)",
        es: "Alá, no hay más dios que Él, el Viviente, el Sustentador. (Verso del Trono, Al-Baqarah 2:255)",
        pt: "Allah, não há divindade senão Ele, o Vivente, o Sustentador. (Ayat al-Kursi, Al-Baqarah 2:255)",
        sw: "Allah, hapana Mungu isipokuwa Yeye, Aliye hai, Anayedumisha viumbe. (Aya ya Kiti, Al-Baqarah 2:255)",
        ha: "Allah, babu wani abin bautawa sai Shi, Mai rai, Mai tsayar da komai. (Ayat al-Kursi, Al-Baqarah 2:255)",
      },
      count: 1,
      source: 'البخاري ٢٣١١، أبو داود ١٥٢٣',
      sourceEn: 'Bukhari 2311, Abu Dawud 1523',
      virtue: {
        ar: 'من قرأ آية الكرسي حين يمسي أُجير من الجن حتى يصبح',
        en: 'Whoever recites Ayat al-Kursi in the evening will be protected from jinn until the morning.',
        fr: "Quiconque récite le Verset du Trône le soir sera protégé des djinns jusqu'au matin.",
        tr: "Akşam Ayetel Kürsi'yi okuyan, sabaha kadar cinlerden korunur.",
        ur: "جو شام کو آیة الکرسی پڑھے وہ صبح تک جنات سے محفوظ رہتا ہے۔",
        id: "Barangsiapa membaca Ayat al-Kursi di sore hari, ia akan dilindungi dari jin hingga pagi hari.",
      },
    },
    {
      id: 'evening_16',
      arabic: '﴿آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّن رُّسُلِهِ ۚ وَقَالُوا سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيرُ ﴿٢٨٥﴾ لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ ۗ رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا ۚ رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِن قَبْلِنَا ۚ رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ۖ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا ۚ أَنتَ مَوْلَانَا فَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ ﴿٢٨٦﴾﴾',
      transliteration: "Amanar-rasulu bima unzila ilayhi min rabbihi wal-mu'minun, kullun amana billahi wa mala'ikatihi wa kutubihi wa rusulihi la nufarriqu bayna ahadin min rusulihi wa qalu sami'na wa ata'na ghufranaka rabbana wa ilaykal-masir. La yukallifullahu nafsan illa wus'aha, laha ma kasabat wa 'alayha maktasabat, rabbana la tu'akhidhna in nasina aw akhta'na, rabbana wa la tahmil 'alayna isran kama hamaltahu 'alal-ladhina min qablina, rabbana wa la tuhammilna ma la taqata lana bihi wa'fu 'anna waghfir lana warhamna anta mawlana fansurna 'alal-qawmil-kafirin.",
      translations: {
        en: "The Messenger has believed in what was revealed to him from his Lord, and so have the believers. All of them have believed in Allah, His angels, His books, and His messengers, saying: We make no distinction between any of His messengers. And they say: We hear and we obey. Grant us Your forgiveness, our Lord. To You is the final destination. Allah does not burden a soul beyond that it can bear. It will have what it has earned, and it will bear what it has incurred. Our Lord, do not impose blame upon us if we forget or err. Our Lord, lay not upon us a burden like that which You laid upon those before us. Our Lord, burden us not with that which we have no ability to bear. And pardon us; and forgive us; and have mercy upon us. You are our protector, so give us victory over the disbelieving people. (Al-Baqarah 2:285-286)",
        fr: "Le Messager a cru en ce qui lui a été révélé de son Seigneur, et les croyants aussi. Tous ont cru en Allah, Ses anges, Ses livres et Ses messagers. Allah n'impose à aucune âme une charge supérieure à sa capacité. (Al-Baqarah 2:285-286)",
        tr: "Peygamber, Rabbi tarafından kendisine indirilene iman etti, müminler de. Allah herhangi bir kişiyi kapasitesinin üzerinde sorumlu tutmaz. (Bakara 2:285-286)",
        ur: "رسول ایمان لائے اس پر جو ان کی طرف رب کی جانب سے نازل کیا گیا اور مومن بھی ایمان لائے۔ اللہ کسی جان کو اس کی طاقت سے زیادہ تکلیف نہیں دیتا۔ (البقرة ٢:٢٨٥-٢٨٦)",
        id: "Rasul telah beriman kepada Al-Quran yang diturunkan kepadanya dari Tuhannya, demikian pula orang-orang yang beriman. Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya. (Al-Baqarah 2:285-286)",
        ms: "Rasul telah beriman dengan apa yang diturunkan kepadanya dari Tuhannya, dan orang-orang yang beriman juga. Allah tidak memberati seseorang melainkan apa yang terdaya olehnya. (Al-Baqarah 2:285-286)",
        fa: "پیامبر به آنچه از پروردگارش بر او نازل شده ایمان آورد و مومنان نیز. خداوند هیچ کس را جز به اندازه توانش تکلیف نمی‌کند. (البقره ۲:۲۸۵-۲۸۶)",
        bn: "রাসূল বিশ্বাস রাখেন তাঁর কাছে তাঁর পালনকর্তার পক্ষ থেকে যা অবতীর্ণ হয়েছে তার প্রতি এবং মুসলমানরাও। আল্লাহ কাউকে তার সাধ্যের বাইরে দায়িত্ব চাপান না। (আল-বাকারা ২:২৮৫-২৮৬)",
        zh: "使者确信从他的主降示他的，信士们也确信。真主不负责任何人超出其能力之外的事。 (牧牛章 2:285-286)",
        ru: "Посланник уверовал в то, что ниспослано ему от его Господа, и верующие тоже. Аллах не возлагает на человека сверх его возможностей. (Аль-Бакара 2:285-286)",
        es: "El Mensajero ha creído en lo que le fue revelado de su Señor, y también los creyentes. Allah no impone a nadie más de lo que puede soportar. (Al-Baqarah 2:285-286)",
        pt: "O Mensageiro acredita no que foi revelado a ele pelo seu Senhor, assim como os crentes. Allah não sobrecarrega uma alma além do que ela pode suportar. (Al-Baqarah 2:285-286)",
        sw: "Mtume amefanya imani na kilichoteremshwa kwake kutoka kwa Mola wake, na waumini pia. Allah hamwongezei mtu mzigo zaidi ya uwezo wake. (Al-Baqarah 2:285-286)",
        ha: "Manzon ya yi imani da abin da aka saukar masa daga Ubangijinsa, da muminai ma. Allah baya kalla wa kowa fiye da iyawarsa. (Al-Baqarah 2:285-286)",
      },
      count: 1,
      source: 'البخاري ٤٠٠٨، مسلم ٨٠٧',
      sourceEn: 'Bukhari 4008, Muslim 807',
      virtue: {
        ar: 'من قرأ الآيتين الأخيرتين من سورة البقرة في ليلة كفتاه',
        en: 'Whoever recites the last two verses of Surah Al-Baqarah at night, they will suffice them.',
        fr: "Quiconque récite les deux derniers versets de la sourate Al-Baqarah la nuit, ils lui suffiront.",
        tr: "Kim gece Bakara suresinin son iki ayetini okursa ona yeterler.",
        ur: "جو رات کو سورة البقرة کی آخری دو آیات پڑھے وہ اسے کافی ہو جاتی ہیں۔",
        id: "Barangsiapa membaca dua ayat terakhir dari Surah Al-Baqarah di malam hari, keduanya akan mencukupinya.",
      },
    },
    {
      id: 'evening_17',
      arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ ﴿١﴾ اللَّهُ الصَّمَدُ ﴿٢﴾ لَمْ يَلِدْ وَلَمْ يُولَدْ ﴿٣﴾ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ ﴿٤﴾',
      transliteration: "Qul huwallahu ahad. Allahus-samad. Lam yalid wa lam yulad. Wa lam yakullahu kufuwan ahad.",
      translations: {
        en: "Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. Nor is there to Him any equivalent. (Surah Al-Ikhlas 112)",
        fr: "Dis: Il est Allah, l'Unique. Allah, le Seul à être imploré. Il n'a jamais engendré, n'a pas été engendré. Et nul n'est égal à Lui. (Sourate Al-Ikhlas 112)",
        tr: "De ki: O, Allah'tır, bir tektir. Allah Samed'dir. O doğurmamış ve doğurulmamıştır. Hiçbir şey O'na denk değildir. (İhlas Suresi 112)",
        ur: "کہو: وہ اللہ ایک ہے، اللہ بے نیاز ہے، نہ اس نے جنا نہ وہ جنا گیا، اور کوئی اس کا ہمسر نہیں۔ (سورة الاخلاص ١١٢)",
        id: "Katakanlah: Dialah Allah, Yang Maha Esa. Allah adalah Tuhan yang bergantung kepada-Nya segala sesuatu. Dia tiada beranak dan tidak pula diperanakkan. Dan tidak ada seorangpun yang setara dengan Dia. (Surah Al-Ikhlas 112)",
        ms: "Katakanlah: Allah itu Maha Esa. Allah yang menjadi tumpuan sekalian makhluk. Ia tiada beranak, dan Ia pula tidak diperanakkan. Dan tidak ada sesiapapun yang serupa denganNya. (Surah Al-Ikhlas 112)",
        fa: "بگو: اوست خداوند یکتا. خداوند بی‌نیاز. نزاد و زاده نشد. و هیچ‌کس همتای او نیست. (سوره الاخلاص ١١٢)",
        bn: "বলুন: তিনি আল্লাহ, এক ও অদ্বিতীয়। আল্লাহ অমুখাপেক্ষী। তিনি কাউকে জন্ম দেননি এবং কেউ তাকে জন্ম দেয়নি। এবং তার সমতুল্য কেউ নেই। (সূরা আল-ইখলাস ১১২)",
        zh: "说：祂是真主，是独一的主。真主是万物所依靠的。祂没有生育，也没有被生育，没有任何物可以和祂相比。 (忠诚章 112)",
        ru: "Скажи: Он — Аллах Единый, Аллах Вечный. Он не родил и не был рождён, и нет никого равного Ему. (Сура Аль-Ихлас 112)",
        es: "Di: Él es Allah, el Único. Allah, el Eterno Refugio. No engendró ni fue engendrado. Y no hay nadie igual a Él. (Sura Al-Ikhlas 112)",
        pt: "Diga: Ele é Allah, o Único. Allah, o Eterno Refúgio. Ele não gerou nem foi gerado. E não há ninguém igual a Ele. (Surah Al-Ikhlas 112)",
        sw: "Sema: Yeye ni Allah, Mmoja. Allah, Anayehitajiwa na wote. Hakuzaa wala hakuzaliwa. Na wala hapana sawa naye yeyote. (Sura Al-Ikhlas 112)",
        ha: "Ka ce: Shi ne Allah, Shi ne Daya. Allah ne Mai zaman kanSa. Bai haifi kowa ba, kuma ba a haife Shi ba. Babu wanda ya yi kama da Shi. (Surar Al-Ikhlas 112)",
      },
      count: 3,
      source: 'أبو داود ٥٠٨٢، النسائي ٥٤٢٨',
      sourceEn: 'Abu Dawud 5082, An-Nasai 5428',
      virtue: {
        ar: 'من قرأ المعوذات ثلاثاً حين يصبح وحين يمسي كفتاه من كل شيء',
        en: "Whoever recites the three Mu'awwidhat three times morning and evening, they suffice for everything.",
        fr: "Quiconque récite les trois Mu'awwidhat trois fois le matin et le soir, elles lui suffisent pour tout.",
        tr: "Sabah ve akşam üç Muavvize'yi üçer kez okuyanın her şeyine kafi gelir.",
        ur: "جو صبح و شام تین معوذات تین بار پڑھے وہ اسے ہر چیز کے لیے کافی ہو جاتی ہیں۔",
        id: "Barangsiapa membaca tiga Mu'awwidhat tiga kali di pagi dan sore hari, keduanya mencukupinya dari segala sesuatu.",
      },
    },
    {
      id: 'evening_18',
      arabic: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ﴿١﴾ مِن شَرِّ مَا خَلَقَ ﴿٢﴾ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ﴿٣﴾ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ﴿٤﴾ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ ﴿٥﴾',
      transliteration: "Qul a'udhu birabbil-falaq. Min sharri ma khalaq. Wa min sharri ghasiqin idha waqab. Wa min sharrin-naffathati fil-'uqad. Wa min sharri hasidin idha hasad.",
      translations: {
        en: "Say: I seek refuge with the Lord of the Daybreak, from the evil of what He has created, from the evil of darkness when it settles, from the evil of those who blow on knots, and from the evil of an envier when he envies. (Surah Al-Falaq 113)",
        fr: "Dis: Je cherche refuge auprès du Seigneur de l'Aube naissante, contre le mal de ce qu'Il a créé, contre le mal de l'obscurité quand elle s'étend, contre le mal de celles qui soufflent sur les nœuds, et contre le mal de l'envieux. (Sourate Al-Falaq 113)",
        tr: "De ki: Yarattığı şeylerin şerrinden, karanlığı çöktüğünde gecenin şerrinden, düğümlere üfleyenlerin şerrinden ve kıskandığında kıskancın şerrinden sabahın Rabbine sığınırım. (Felak Suresi 113)",
        ur: "کہو: میں پناہ لیتا ہوں طلوع صبح کے رب کی، ہر اس چیز کے شر سے جو اس نے پیدا کی، اندھیری رات کے شر سے۔ (سورة الفلق ١١٣)",
        id: "Katakanlah: Aku berlindung kepada Tuhan yang menguasai subuh, dari kejahatan makhluk-Nya, dari kejahatan malam apabila telah gelap gulita. (Surah Al-Falaq 113)",
        ms: "Katakanlah: Aku berlindung dengan Tuhan yang mencetuskan fajar, dari kejahatan segala yang Dia ciptakan. (Surah Al-Falaq 113)",
        fa: "بگو: پناه می‌برم به پروردگار سپیده‌دم، از شر آنچه آفریده. (سوره الفلق ١١٣)",
        bn: "বলুন: আমি আশ্রয় প্রার্থনা করছি উষার প্রভুর কাছে। (সূরা আল-ফালাক ১১৩)",
        zh: "说：我寻求晨光之主的庇护，免受祂所造之物的伤害。 (法莱格章 113)",
        ru: "Скажи: Прибегаю к защите Господа рассвета от зла того, что Он сотворил. (Сура Аль-Фалак 113)",
        es: "Di: Me refugio en el Señor del Amanecer, del mal de lo que ha creado. (Sura Al-Falaq 113)",
        pt: "Diga: Busco refúgio no Senhor do Amanhecer, do mal do que Ele criou. (Surah Al-Falaq 113)",
        sw: "Sema: Ninajikinga kwa Mola wa mapambazuko. (Sura Al-Falaq 113)",
        ha: "Ka ce: Ina neman tsari a wajen Ubangijin alfijir. (Surar Al-Falaq 113)",
      },
      count: 3,
      source: 'أبو داود ٥٠٨٢، النسائي ٥٤٢٨',
      sourceEn: 'Abu Dawud 5082, An-Nasai 5428',
    },
    {
      id: 'evening_19',
      arabic: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ ﴿١﴾ مَلِكِ النَّاسِ ﴿٢﴾ إِلَٰهِ النَّاسِ ﴿٣﴾ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ﴿٤﴾ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ﴿٥﴾ مِنَ الْجِنَّةِ وَالنَّاسِ ﴿٦﴾',
      transliteration: "Qul a'udhu birabbin-nas. Malikin-nas. Ilahin-nas. Min sharril-waswasil-khannas. Alladhi yuwaswisu fi sudurin-nas. Minal-jinnati wan-nas.",
      translations: {
        en: "Say: I seek refuge with the Lord of mankind, the King of mankind, the God of mankind, from the evil of the sneaking whisperer, who whispers in the hearts of mankind, from among the jinn and mankind. (Surah An-Nas 114)",
        fr: "Dis: Je cherche refuge auprès du Seigneur des hommes, du Roi des hommes, du Dieu des hommes, contre le mal du tentateur sournois qui souffle le mal dans les cœurs des hommes. (Sourate An-Nas 114)",
        tr: "De ki: İnsanların Rabbine, insanların Melikine, insanların İlahına sığınırım; sinsi vesvesecinin şerrinden. (Nas Suresi 114)",
        ur: "کہو: میں پناہ لیتا ہوں لوگوں کے رب کی، لوگوں کے بادشاہ کی، لوگوں کے معبود کی، وسوسہ ڈالنے والے کے شر سے۔ (سورة الناس ١١٤)",
        id: "Katakanlah: Aku berlindung kepada Tuhan manusia, Raja manusia, Sesembahan manusia, dari kejahatan bisikan yang biasa bersembunyi. (Surah An-Nas 114)",
        ms: "Katakanlah: Aku berlindung dengan Tuhan manusia, Raja manusia, Tuhan yang disembah oleh manusia. (Surah An-Nas 114)",
        fa: "بگو: پناه می‌برم به پروردگار مردم، پادشاه مردم، معبود مردم. (سوره الناس ١١٤)",
        bn: "বলুন: আমি মানুষের প্রভুর আশ্রয় চাই, মানুষের অধিপতির, মানুষের উপাস্যের কাছে। (সূরা আন-নাস ১১৪)",
        zh: "说：我寻求人类之主的庇护，人类之王，人类之神。 (人章 114)",
        ru: "Скажи: Прибегаю к защите Господа людей, Царя людей, Бога людей. (Сура Ан-Нас 114)",
        es: "Di: Me refugio en el Señor de la humanidad, el Rey de la humanidad, el Dios de la humanidad. (Sura An-Nas 114)",
        pt: "Diga: Busco refúgio no Senhor da humanidade, no Rei da humanidade, no Deus da humanidade. (Surah An-Nas 114)",
        sw: "Sema: Ninajikinga kwa Mola wa watu, Mfalme wa watu, Mungu wa watu. (Sura An-Nas 114)",
        ha: "Ka ce: Ina neman tsari a wajen Ubangijin mutane, Sarkin mutane, Ilahin mutane. (Surar An-Nas 114)",
      },
      count: 3,
      source: 'أبو داود ٥٠٨٢، النسائي ٥٤٢٨',
      sourceEn: 'Abu Dawud 5082, An-Nasai 5428',
    },
    {
      id: 'evening_01',
      arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذِهِ اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهَا، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذِهِ اللَّيْلَةِ وَشَرِّ مَا بَعْدَهَا، رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ، رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ',
      transliteration: "Amsayna wa amsal-mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah, lahul-mulku walahul-hamdu wa huwa 'ala kulli shay'in qadir. Rabbi as'aluka khayra ma fi hadhihil-laylati wa khayra ma ba'daha, wa a'udhu bika min sharri ma fi hadhihil-laylati wa sharri ma ba'daha. Rabbi a'udhu bika minal-kasali wa su'il-kibar. Rabbi a'udhu bika min 'adhabin fin-nar wa 'adhabin fil-qabr.",
      translations: {
        en: "We have reached the evening and at this very time unto Allah belongs all sovereignty, and all praise is for Allah. None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and praise, and He is over all things omnipotent. My Lord, I ask You for the good of this night and the good of what follows it, and I take refuge in You from the evil of this night and the evil of what follows it. My Lord, I take refuge in You from laziness and the misery of old age. My Lord, I take refuge in You from torment in the Fire and punishment in the grave.",
        fr: "Nous voici au soir, et en ce moment toute la souveraineté appartient à Allah, toute la louange est à Allah. Nul n'a le droit d'être adoré sauf Allah, seul, sans associé. À Lui appartient toute souveraineté et toute louange, et Il est Omnipotent sur toute chose.",
        tr: "Akşama eriştik ve akşama erdi mülk Allah'a aittir. Hamd Allah'a mahsustur. Allah'tan başka ilah yoktur, O tektir, ortağı yoktur. Mülk O'nundur, hamd O'nundur ve O her şeye kadirdir.",
        ur: "ہم نے شام کی اور شام کی ملک اللہ کے لیے، حمد اللہ کے لیے، اللہ کے سوا کوئی معبود نہیں، وہ اکیلا ہے، اس کا کوئی شریک نہیں۔",
        id: "Kami telah memasuki waktu sore dan kerajaan hanya milik Allah, segala puji bagi Allah. Tiada Tuhan yang berhak disembah kecuali Allah semata, tiada sekutu bagi-Nya.",
        ms: "Kami telah memasuki waktu petang, dan pada waktu ini kerajaan hanya milik Allah, segala puji bagi Allah.",
        fa: "شب کردیم و شب کرد ملک برای خداوند و حمد برای خداوند است.",
      },
      count: 1,
      source: 'مسلم ٢٧٢٣',
      sourceEn: 'Muslim 2723',
    },
    {
      id: 'evening_02',
      arabic: 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ',
      transliteration: "Allahumma bika amsayna, wa bika asbahna, wa bika nahya, wa bika namutu, wa ilaykal-masir.",
      translations: {
        en: "O Allah, by Your leave we have reached the evening and by Your leave we have reached the morning, by Your leave we live and die and unto You is our return.",
        fr: "Ô Allah, c'est grâce à Toi que nous avons atteint le soir, et c'est grâce à Toi que nous atteignons le matin, c'est grâce à Toi que nous vivons et mourons, et vers Toi est le retour.",
        tr: "Allah'ım! Senin izninle akşama eriştik, Senin izninle sabaha eriştik, Seninle yaşar Seninle ölürüz ve dönüş Sanadır.",
        ur: "اے اللہ! تیری توفیق سے ہم نے شام کی اور تیری توفیق سے صبح کریں گے، تیرے ساتھ جیتے ہیں اور تیرے ساتھ مرتے ہیں، اور تیری طرف لوٹنا ہے۔",
        id: "Ya Allah, dengan-Mu kami memasuki waktu sore, dan dengan-Mu kami memasuki waktu pagi, dengan-Mu kami hidup, dengan-Mu kami mati, dan kepada-Mu tempat kembali.",
        ms: "Ya Allah, dengan-Mu kami melalui petang hari, dengan-Mu kami melalui pagi hari, dengan-Mu kami hidup dan mati, dan kepada-Mu kami akan kembali.",
        fa: "بارخدایا! به یاری تو وارد شب شدیم و به یاری تو صبح را سپری کردیم، با تو زندگی می‌کنیم و با تو می‌میریم و بازگشت به سوی توست.",
      },
      count: 1,
      source: 'أبو داود ٥٠٦٨، الترمذي ٣٣٩١',
      sourceEn: 'Abu Dawud 5068, Tirmidhi 3391',
    },
    {
      id: 'evening_03',
      arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
      transliteration: "Allahumma anta rabbi la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't, a'udhu bika min sharri ma sana't, abu'u laka bini'matika 'alayy, wa abu'u bidhanbi faghfir li fa innahu la yaghfirudh-dhunuba illa ant.",
      translations: {
        en: "O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I abide to Your covenant and promise as best I can. I take refuge in You from the evil of which I have committed. I acknowledge Your favour upon me and I acknowledge my sin, so forgive me, for verily none can forgive sin except You.",
        fr: "Ô Allah, Tu es mon Seigneur, nul n'a le droit d'être adoré sauf Toi. Tu m'as créé et je suis Ton serviteur. Je m'attiens à Ton alliance et à Ta promesse autant que je peux. Je reconnais Tes bienfaits sur moi et je reconnais mes péchés, alors pardonne-moi.",
        tr: "Allah'ım! Sen benim Rabbimsin, Senden başka ilah yoktur. Sen beni yarattın, ben Senin kulunum.",
        ur: "اے اللہ! تو میرا رب ہے، تیرے سوا کوئی معبود نہیں۔ تو نے مجھے پیدا کیا اور میں تیرا بندہ ہوں۔",
        id: "Ya Allah, Engkau adalah Tuhanku, tidak ada Tuhan yang berhak disembah kecuali Engkau.",
        ms: "Ya Allah, Engkaulah Tuhanku, tiada tuhan selain-Mu.",
        fa: "بارخدایا! تو پروردگار من هستی، جز تو معبودی نیست.",
      },
      count: 1,
      source: 'البخاري ٦٣٠٦',
      sourceEn: 'Bukhari 6306',
      virtue: {
        ar: 'من قالها موقناً بها فمات من ليلته قبل أن يصبح فهو من أهل الجنة',
        en: 'Whoever says it with certainty and dies that night before morning, they are among the people of Paradise.',
        fr: "Quiconque le dit avec certitude et meurt cette nuit-là avant le matin, il fait partie des gens du Paradis.",
        tr: "Kim buna inanarak söyler de o gecenin sabahına ulaşmadan ölürse, Cennet ehlinden olur.",
        ur: "جو اسے یقین کے ساتھ پڑھے اور اس رات صبح سے پہلے مر جائے تو وہ جنتیوں میں سے ہے۔",
      },
    },
    {
      id: 'evening_04',
      arabic: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلَهَ إِلَّا أَنْتَ',
      transliteration: "Allahumma 'afini fi badani, Allahumma 'afini fi sam'i, Allahumma 'afini fi basari, la ilaha illa ant.",
      translations: {
        en: "O Allah, grant my body health. O Allah, grant my hearing health. O Allah, grant my sight health. None has the right to be worshipped except You.",
        fr: "Ô Allah, accorde la santé à mon corps. Ô Allah, accorde la santé à mon ouïe. Ô Allah, accorde la santé à ma vue. Nul n'a le droit d'être adoré sauf Toi.",
        tr: "Allah'ım! Bedenime afiyet ver, Allah'ım! Kulağıma afiyet ver, Allah'ım! Gözüme afiyet ver.",
        ur: "اے اللہ! میرے جسم کو عافیت دے، میری سماعت کو عافیت دے، میری بصارت کو عافیت دے۔",
        id: "Ya Allah, berilah kesehatan pada tubuhku. Ya Allah, berilah kesehatan pada pendengaranku. Ya Allah, berilah kesehatan pada penglihatanku.",
        ms: "Ya Allah, kurniakanlah kesihatan pada badanku. Ya Allah, kurniakanlah kesihatan pada pendengaranku. Ya Allah, kurniakanlah kesihatan pada penglihatanku.",
        fa: "خدایا! به تن من عافیت بده، به شنوایی من عافیت بده، به بینایی من عافیت بده.",
      },
      count: 3,
      source: 'أبو داود ٥٠٩٠',
      sourceEn: 'Abu Dawud 5090',
    },
    {
      id: 'evening_05',
      arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
      transliteration: "Bismillahil-ladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'i wa huwas-sami'ul-'alim.",
      translations: {
        en: "In the name of Allah with whose name nothing is harmed on earth nor in the heavens, and He is the All-Seeing, the All-Knowing.",
        fr: "Au nom d'Allah, par le nom duquel rien ne peut nuire sur la terre ni dans les cieux, et Il est le Tout-Entendant, l'Omniscient.",
        tr: "Allah'ın adıyla, Yerde ve gökte O'nun adıyla hiçbir şey zarar vermez. O işitendir, bilendir.",
        ur: "اللہ کے نام سے جس کے نام کے ساتھ زمین و آسمان میں کوئی چیز نقصان نہیں پہنچاتی۔",
        id: "Dengan nama Allah yang dengan nama-Nya tidak ada sesuatu pun yang membahayakan di bumi maupun di langit.",
        ms: "Dengan nama Allah yang dengan nama-Nya tidak ada sesuatu yang membahayakan di bumi dan di langit.",
        fa: "به نام خداوندی که با نام او هیچ چیزی زیان نمی‌رساند.",
      },
      count: 3,
      source: 'أبو داود ٥٠٨٨، الترمذي ٣٣٨٨',
      sourceEn: 'Abu Dawud 5088, Tirmidhi 3388',
    },
    {
      id: 'evening_06',
      arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا',
      transliteration: "Raditu billahi rabban, wa bil-islami dinan, wa bi-muhammadin sallallahu 'alayhi wa sallam nabiyya.",
      translations: {
        en: "I am pleased with Allah as my Lord, with Islam as my religion and with Muhammad (peace be upon him) as my Prophet.",
        fr: "Je suis satisfait d'Allah comme Seigneur, de l'Islam comme religion et de Muhammad (paix sur lui) comme prophète.",
        tr: "Allah'ı Rab, İslam'ı din, Hz. Muhammed'i (s.a.v.) peygamber olarak kabul etmekten razıyım.",
        ur: "میں اللہ کے رب ہونے، اسلام کے دین ہونے اور محمد ﷺ کے نبی ہونے پر راضی ہوں۔",
        id: "Aku rela Allah sebagai Tuhanku, Islam sebagai agamaku dan Muhammad shallallahu 'alaihi wa sallam sebagai nabiku.",
        ms: "Aku redha dengan Allah sebagai Tuhanku, Islam sebagai agamaku dan Muhammad S.A.W sebagai nabiku.",
        fa: "به خداوند به عنوان پروردگار، به اسلام به عنوان دین و به محمد صلی الله علیه وسلم به عنوان پیامبر راضی هستم.",
      },
      count: 3,
      source: 'أبو داود ٥٠٧٢',
      sourceEn: 'Abu Dawud 5072',
    },
    {
      id: 'evening_07',
      arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ',
      transliteration: "Ya Hayyu ya Qayyumu birahmatika astaghith, aslih li sha'ni kullahu, wa la takilni ila nafsi tarfata 'ayn.",
      translations: {
        en: "O Ever-Living, O Self-Subsisting, by Your mercy I seek relief. Rectify all my affairs and do not leave me to myself, even for the blink of an eye.",
        fr: "Ô Vivant, Ô Subsistant par Lui-même! C'est par Ta miséricorde que j'implore Ton aide. Arrange-moi toutes mes affaires et ne me laisse pas à moi-même.",
        tr: "Ey Hay, ey Kayyum! Rahmetinle senden yardım diliyorum. Bütün işlerimi düzelt ve beni bir göz kırpması kadar bile nefsimle başbaşa bırakma.",
        ur: "اے حی! اے قیوم! تیری رحمت کے وسیلے سے فریاد کرتا ہوں، میرے تمام معاملات درست فرما دے۔",
        id: "Wahai Yang Maha Hidup, wahai Yang Maha Berdiri sendiri, dengan rahmat-Mu aku memohon pertolongan.",
        ms: "Wahai Yang Maha Hidup, Wahai Yang Maha Berdiri Sendiri! Dengan rahmat-Mu aku memohon pertolongan.",
        fa: "ای زنده پاینده! به رحمتت پناه می‌برم، تمام کارهایم را اصلاح کن.",
      },
      count: 3,
      source: 'النسائي في الكبرى ٩٨٣٨',
      sourceEn: "An-Nasa'i (Al-Kubra) 9838",
    },
    {
      id: 'evening_08',
      arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالآخِرَةِ، اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي',
      transliteration: "Allahumma inni as'alukal-'afwa wal-'afiyah fid-dunya wal-akhirah. Allahumma inni as'alukal-'afwa wal-'afiyah fi dini wa dunya-ya wa ahli wa mali.",
      translations: {
        en: "O Allah, I ask You for pardon and well-being in this life and the next. O Allah, I ask You for pardon and well-being in my religious and worldly affairs, and my family and my wealth.",
        fr: "Ô Allah, je Te demande le pardon et le bien-être dans ce monde et dans l'au-delà.",
        tr: "Allah'ım! Senden dünya ve ahirette af ve afiyet istiyorum.",
        ur: "اے اللہ! دنیا اور آخرت میں عفو و عافیت مانگتا ہوں۔",
        id: "Ya Allah, aku memohon kepada-Mu maaf dan keselamatan di dunia dan akhirat.",
        ms: "Ya Allah, aku memohon keampunan dan keselamatan di dunia dan akhirat.",
        fa: "خدایا! در دنیا و آخرت از تو عفو و عافیت می‌خواهم.",
      },
      count: 1,
      source: 'أبو داود ٥٠٧٤',
      sourceEn: 'Abu Dawud 5074',
    },
    {
      id: 'evening_09',
      arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
      transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq.",
      translations: {
        en: "I take refuge in the Perfect Words of Allah from the evil of what He has created.",
        fr: "Je cherche refuge auprès des Paroles parfaites d'Allah contre le mal de ce qu'Il a créé.",
        tr: "Allah'ın yarattıklarının şerrinden O'nun eksiksiz kelimelerine sığınırım.",
        ur: "اللہ کے کامل کلمات کی پناہ لیتا ہوں اس کی تمام مخلوقات کے شر سے۔",
        id: "Aku berlindung dengan kalimat-kalimat Allah yang sempurna dari kejahatan makhluk yang Allah ciptakan.",
        ms: "Aku berlindung dengan kalimat-kalimat Allah yang sempurna daripada kejahatan apa yang telah Dia ciptakan.",
        fa: "پناه می‌برم به کلمات کامل الهی از شر آنچه آفریده است.",
      },
      count: 3,
      source: 'مسلم ٢٧٠٩',
      sourceEn: 'Muslim 2709',
    },
    {
      id: 'evening_10',
      arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
      transliteration: "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadir.",
      translations: {
        en: "None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and praise, and He is over all things omnipotent.",
        fr: "Nul n'a le droit d'être adoré sauf Allah, seul, sans associé. À Lui appartient toute souveraineté et toute louange.",
        tr: "Allah'tan başka ilah yoktur. O tektir, ortağı yoktur. Mülk O'nundur, hamd O'nundur.",
        ur: "اللہ کے سوا کوئی معبود نہیں، وہ اکیلا ہے، اس کا کوئی شریک نہیں۔",
        id: "Tidak ada tuhan yang berhak disembah selain Allah semata, tidak ada sekutu bagi-Nya.",
        ms: "Tiada tuhan selain Allah semata-mata, tiada sekutu bagi-Nya.",
        fa: "هیچ معبودی جز الله نیست، یگانه‌ای بی‌شریک.",
      },
      count: 10,
      source: 'البخاري ٦٤٠٤، مسلم ٢٦٩٢',
      sourceEn: 'Bukhari 6404, Muslim 2692',
    },
    {
      id: 'evening_11',
      arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
      transliteration: "Subhanallahi wa bihamdih.",
      translations: {
        en: "Glory be to Allah and praise be to Him.",
        fr: "Gloire à Allah et que la louange Lui soit rendue.",
        tr: "Allah'ı tüm noksan sıfatlardan tenzih eder ve O'na hamdederim.",
        ur: "اللہ پاک ہے اور اس کی حمد کے ساتھ۔",
        id: "Maha Suci Allah dan segala puji bagi-Nya.",
        ms: "Maha Suci Allah dan segala puji bagi-Nya.",
        fa: "خداوند منزه است و ستایش او را می‌گویم.",
        bn: "আল্লাহ পবিত্র এবং তাঁর প্রশংসা।",
        zh: "赞美真主，并感谢他。",
        ru: "Слава Аллаху и хвала Ему.",
      },
      count: 100,
      source: 'البخاري ٦٤٠٥، مسلم ٢٦٩١',
      sourceEn: 'Bukhari 6405, Muslim 2691',
    },
    {
      id: 'evening_12',
      arabic: 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ',
      transliteration: "Allahumma salli wa sallim 'ala nabiyyina Muhammad.",
      translations: {
        en: "O Allah, send peace and blessings upon our Prophet Muhammad.",
        fr: "Ô Allah, envoie Ta grâce et Ta paix sur notre Prophète Mohammed.",
        tr: "Allah'ım! Peygamberimiz Muhammed'e salât ve selam eyle.",
        ur: "اے اللہ! ہمارے نبی محمد ﷺ پر درود و سلام نازل فرما۔",
        id: "Ya Allah, limpahkanlah shalawat dan salam kepada Nabi kami Muhammad.",
        ms: "Ya Allah, selawat dan salam ke atas Nabi kami Muhammad.",
        fa: "خدایا! بر پیامبرمان محمد درود و سلام بفرست.",
        bn: "হে আল্লাহ! আমাদের নবী মুহাম্মদের উপর দরুদ ও সালাম পাঠাও।",
        zh: "愿安拉赐福我们的先知穆罕默德。",
        ru: "О Аллах, благослови нашего Пророка Мухаммада и приветствуй его.",
      },
      count: 10,
      source: 'الطبراني، صحيح الجامع ٦٣٥٧',
      sourceEn: "Al-Tabarani, Sahih al-Jami' 6357",
    },
    {
      id: 'evening_13',
      arabic: 'اللَّهُمَّ إِنِّي أَمْسَيْتُ أُشْهِدُكَ وَأُشْهِدُ حَمَلَةَ عَرْشِكَ وَمَلَائِكَتَكَ وَجَمِيعَ خَلْقِكَ، أَنَّكَ أَنْتَ اللَّهُ لَا إِلَهَ إِلَّا أَنْتَ وَحْدَكَ لَا شَرِيكَ لَكَ، وَأَنَّ مُحَمَّدًا عَبْدُكَ وَرَسُولُكَ',
      transliteration: "Allahumma inni amsaytu ushhiduka wa ushhidu hamalata 'arshika wa mala'ikataka wa jami'a khalqika, annaka antallahu la ilaha illa anta wahdaka la sharika lak, wa anna muhammadan 'abduka wa rasuluk.",
      translations: {
        en: "O Allah, I have reached the evening and call upon You to witness, and I call upon the bearers of Your Throne, Your angels, and all of Your creation to witness, that You are Allah, none has the right to be worshipped except You, alone, without partner, and that Muhammad is Your servant and messenger.",
        fr: "Ô Allah, je suis parvenu au soir et je Te prends à témoin, et je prends à témoin les porteurs de Ton Trône, Tes anges, et toute Ta création, que Tu es Allah, nul n'a le droit d'être adoré sauf Toi, seul, sans associé, et que Muhammad est Ton serviteur et messager.",
        tr: "Allah'ım! Akşamladım. Seni, Arş'ını taşıyanları, meleklerini ve bütün yaratıklarını şahit tutuyorum ki Sen Allah'sın, Senden başka ilah yoktur, tek ve ortaksızsın, Muhammed Senin kulun ve elçindir.",
        ur: "اے اللہ! میں نے شام کی، میں تجھے، تیرے عرش اٹھانے والوں، فرشتوں اور تمام مخلوق کو گواہ بناتا ہوں کہ تو اللہ ہے، تیرے سوا کوئی معبود نہیں۔",
        id: "Ya Allah, aku memasuki waktu sore dengan menjadikan-Mu sebagai saksi, juga para malaikat pemikul Arsy-Mu, para malaikat-Mu, dan seluruh makhluk-Mu, bahwa sesungguhnya Engkau adalah Allah, tiada Tuhan selain Engkau.",
        ms: "Ya Allah, aku telah memasuki waktu petang sambil menjadikan-Mu sebagai saksi dan juga para malaikat pemikul Arasy-Mu, para malaikat-Mu dan semua makhluk-Mu.",
        fa: "خدایا! شب کردم و تو و حاملان عرشت و فرشتگانت و همه مخلوقاتت را گواه می‌گیرم.",
      },
      count: 4,
      source: 'أبو داود ٥٠٨٣، صحيح',
      sourceEn: 'Abu Dawud 5083, Sahih',
      virtue: {
        ar: 'أعتقه الله من النار',
        en: 'Allah will free them from the Fire.',
        fr: "Allah les affranchira du Feu.",
        tr: "Allah onu ateşten azad eder.",
        ur: "اللہ اسے جہنم سے آزاد کر دے گا۔",
      },
    },
    {
      id: 'evening_14',
      arabic: 'اللَّهُمَّ مَا أَمْسَى بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ، فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ',
      transliteration: "Allahumma ma amsa bi min ni'matin aw bi'ahadin min khalqika faminka wahdaka la sharika lak, falakal-hamdu wa lakash-shukr.",
      translations: {
        en: "O Allah, what blessing I or any of Your creation have reached this evening, is from You alone, without partner, so for You is all praise and unto You all thanks.",
        fr: "Ô Allah, les bienfaits dont je jouis ce soir, ou dont jouit l'une de Tes créatures, viennent de Toi seul, sans associé, alors à Toi est toute la louange et toute la reconnaissance.",
        tr: "Allah'ım! Bu akşam bende ya da yaratıklarından birinde bulunan her nimet, yalnız Senden, ortaksız Senden. Hamd Senindir, şükür Senindir.",
        ur: "اے اللہ! اس شام میں یا تیری کسی مخلوق کے پاس جو بھی نعمت ہے وہ صرف تیری طرف سے ہے، کوئی شریک نہیں، پس تیرے لیے ہی حمد ہے اور تیرا ہی شکر ہے۔",
        id: "Ya Allah, nikmat yang ada padaku atau pada salah seorang dari makhluk-Mu di sore ini adalah dari-Mu semata, tiada sekutu bagi-Mu. Maka hanya bagi-Mu segala puji dan syukur.",
        ms: "Ya Allah, apa jua nikmat yang ada padaku atau pada mana-mana makhluk-Mu petang ini adalah dari-Mu semata-mata, tiada sekutu bagi-Mu.",
        fa: "خدایا! هر نعمتی که در این شب برای من یا برای هر کدام از مخلوقاتت باشد، تنها از توست، شریکی نداری.",
      },
      count: 1,
      source: 'أبو داود ٥٠٧٣، صحيح',
      sourceEn: 'Abu Dawud 5073, Sahih',
    },
    {
      id: 'evening_20',
      arabic: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
      transliteration: "Hasbiyallahu la ilaha illa huwa 'alayhi tawakkaltu wa huwa rabbul-'arshil-'azim.",
      translations: {
        en: "Allah is sufficient for me. There is no god but He. In Him I put my trust, and He is the Lord of the Mighty Throne.",
        fr: "Allah me suffit. Il n'y a point de divinité sauf Lui. En Lui je place ma confiance, et Il est le Seigneur du Trône immense.",
        tr: "Allah bana yeter. O'ndan başka ilah yoktur. O'na tevekkül ettim. O, büyük Arş'ın Rabbidir.",
        ur: "اللہ مجھے کافی ہے، اس کے سوا کوئی معبود نہیں، میں نے اسی پر بھروسہ کیا اور وہ عرش عظیم کا رب ہے۔",
        id: "Cukuplah Allah bagiku. Tidak ada tuhan selain Dia. Kepada-Nya aku bertawakkal dan Dia adalah Tuhan Arsy yang agung.",
        ms: "Cukuplah Allah bagiku. Tiada tuhan selain-Nya. Kepada-Nya aku bertawakkal dan Dia adalah Tuhan Arasy yang agung.",
        fa: "خداوند برایم کافی است. جز او معبودی نیست. بر او توکل کردم.",
        bn: "আল্লাহই আমার জন্য যথেষ্ট। তিনি ছাড়া কোনো উপাস্য নেই। তাঁর উপরই আমি ভরসা করি।",
        zh: "真主对我来说就足够了。除祂外别无神。我信赖祂，祂是伟大宝座的主。",
        ru: "Мне достаточно Аллаха. Нет бога, кроме Него. На Него я уповаю.",
        es: "Allah me es suficiente. No hay dios excepto Él. En Él confío.",
        pt: "Allah é suficiente para mim. Não há deus exceto Ele. Nele deposito minha confiança.",
        sw: "Allah yanitosha. Hapana Mungu ila Yeye. Kwake ninategemea.",
        ha: "Allah ya ishe ni. Babu abin bautawa sai Shi. A kansa na dogara.",
      },
      count: 7,
      source: 'أبو داود ٥٠٨١، صحيح',
      sourceEn: 'Abu Dawud 5081, Sahih',
      virtue: {
        ar: 'من قالها سبع مرات حين يصبح وحين يمسي كفاه الله ما أهمه من أمر الدنيا والآخرة',
        en: 'Whoever says it seven times morning and evening, Allah will spare them whatever worries them of worldly and religious affairs.',
        fr: "Quiconque la dit sept fois le matin et le soir, Allah lui suffira dans ce qui l'inquiète.",
        tr: "Kim sabah akşam yedi kez söylerse Allah dünya ve ahiret işlerinde onu endişelendiren şeylerde ona yeter.",
        ur: "جو صبح و شام سات بار پڑھے اللہ اسے دنیا و آخرت کے معاملات میں کافی ہو جاتا ہے۔",
        id: "Barangsiapa mengucapkannya tujuh kali pagi dan sore, Allah akan mencukupinya dari segala yang mengkhawatirkannya.",
      },
    },
    {
      id: 'evening_21',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، لَا إِلَهَ إِلَّا أَنْتَ',
      transliteration: "Allahumma inni a'udhu bika minal-kufri wal-faqr, wa a'udhu bika min 'adhabil-qabr, la ilaha illa ant.",
      translations: {
        en: "O Allah, I seek refuge in You from disbelief and poverty, and I seek refuge in You from the punishment of the grave. None has the right to be worshipped except You.",
        fr: "Ô Allah, je cherche refuge auprès de Toi contre la mécréance et la pauvreté, et je cherche refuge auprès de Toi contre le châtiment de la tombe.",
        tr: "Allah'ım! Küfürden ve fakirlikten Sana sığınırım, kabir azabından da Sana sığınırım.",
        ur: "اے اللہ! میں کفر اور فقر سے تیری پناہ مانگتا ہوں، اور عذاب قبر سے تیری پناہ مانگتا ہوں۔",
        id: "Ya Allah, aku berlindung kepada-Mu dari kekufuran dan kefakiran, dan aku berlindung kepada-Mu dari azab kubur.",
        ms: "Ya Allah, aku berlindung kepada-Mu daripada kekufuran dan kemiskinan, dan aku berlindung kepada-Mu daripada azab kubur.",
        fa: "خدایا! از کفر و فقر به تو پناه می‌برم، و از عذاب قبر به تو پناه می‌برم.",
        bn: "হে আল্লাহ! আমি কুফর ও দারিদ্র্য থেকে তোমার আশ্রয় চাই, এবং কবরের আযাব থেকে তোমার আশ্রয় চাই।",
        zh: "主啊，我向你寻求庇护，免遭不信和贫困，我向你寻求庇护，免受墓中之苦。",
        ru: "О Аллах, я прибегаю к Тебе от неверия и бедности, и прибегаю к Тебе от мучений в могиле.",
        es: "Oh Allah, me refugio en Ti del descreer y de la pobreza, y me refugio en Ti del castigo de la tumba.",
        pt: "Ó Allah, refugio-me em Ti da descrença e da pobreza, e refugio-me em Ti do castigo do túmulo.",
        sw: "Ewe Mwenyezi Mungu, ninakukimbilia kutokana na ukafiri na umasikini, na azabu ya kaburi.",
        ha: "Ya Allah, ina neman tsarinKa daga kafirci da talauci, da azabar kabari.",
      },
      count: 3,
      source: 'أبو داود ٥٠٩٠، صحيح',
      sourceEn: 'Abu Dawud 5090, Sahih',
    },
  ],
};

export default ATHKAR;

export function getThikrTranslation(thikr: Thikr, lang: string): string {
  return thikr.translations[lang] ?? thikr.translations['en'] ?? '';
}

export function getThikrVirtue(thikr: Thikr, lang: string): string | undefined {
  if (!thikr.virtue) return undefined;
  return thikr.virtue[lang] ?? thikr.virtue['en'];
}
